"""
Agent Prompt Service

v2.337.0 — the four per-workflow prompts (plan generation, execution, recon,
assist) collapse into ONE session prompt.  A single project-scoped session
lets the agent query the inventory, scan and upload, register a plan and
execute it, and record what it found; the operational detail for each of
those is served by the workflow-sliced guide (``/agents-guide?workflow=…``)
and by the read-back each phase-start endpoint returns, not by four separate
start prompts.

``build_session_instructions`` is the session-start block.  The per-phase
read-backs live in ``agent_policy.render_phase_read_back`` and are emitted by
the phase-start endpoints.

The ``PROMPT_VERSION`` constant MUST be bumped whenever the instruction content
changes in a way that affects agent behavior — prepend an entry to
``PROMPT_VERSION_HISTORY`` in ``agent_prompt_history`` (the constant is derived
from the newest entry, so version and changelog can't drift).
"""

import logging
from typing import Any, Optional

from fastapi import Request

from app.core.config import settings
from app.services.agent_prompt_history import PROMPT_VERSION
from app.services.agent_policy import (
    render_read_back,
    render_key_expiry_guidance,
    render_safety_rules,
)

logger = logging.getLogger(__name__)


_INSTANCE_ID_CACHE: Optional[str] = None


def _load_instance_id() -> Optional[str]:
    """Look up the system identity UUID for the provenance block.

    Returns None if the row isn't seeded yet (first boot). Logs at exception
    level for any other failure so a real bootstrap problem surfaces.
    """
    global _INSTANCE_ID_CACHE
    if _INSTANCE_ID_CACHE is not None:
        return _INSTANCE_ID_CACHE
    from sqlalchemy.exc import OperationalError, ProgrammingError
    try:
        from app.db.session import SessionLocal
        from app.db.models_auth import SystemIdentity
        with SessionLocal() as db:
            row = db.query(SystemIdentity).order_by(SystemIdentity.id).first()
            _INSTANCE_ID_CACHE = row.instance_id if row else None
            return _INSTANCE_ID_CACHE
    except (OperationalError, ProgrammingError) as exc:
        logger.warning(
            "system_identity lookup failed (db or schema unavailable); "
            "provenance block will show '(pending)': %s", exc,
        )
        return None
    except Exception:
        logger.exception(
            "Unexpected error loading system_identity for provenance block; "
            "provenance block will show '(pending)' but check the bootstrap path"
        )
        return None


def build_provenance_block(
    *,
    base_url: str,
    user_label: str,
    user_id: Optional[int],
    action: str,
    target_label: str,
    timestamp_iso: str,
) -> str:
    """Prepend the standardized provenance + identity-check header to a prompt."""
    instance_id = _load_instance_id() or "(pending — retry after first boot)"
    origin = base_url.rsplit("/api/v1", 1)[0]
    user_suffix = f" (id {user_id})" if user_id is not None else ""
    return (
        f"## Provenance\n\n"
        f"This prompt was generated by BlueStick instance "
        f"`{instance_id}` at {timestamp_iso}.\n\n"
        f"- **Authorized by:** {user_label}{user_suffix}\n"
        f"- **Action:** {action}\n"
        f"- **Target:** {target_label}\n"
        f"- **Instance base URL:** {origin}\n\n"
        f"### Verify once before starting\n\n"
        f"```\n"
        f"curl -s {origin}/.well-known/networkmapper.json\n"
        f"```\n\n"
        f"Confirm the response contains `\"instance_id\": \"{instance_id}\"` "
        f"and `\"name\": \"BlueStick\"`. If either does not match, "
        f"**stop** and alert the user — the prompt may have been tampered "
        f"with, copied from a different instance, or served by an unrelated "
        f"host. Once verified, the session is trusted for the duration of "
        f"your API key; you do not need to re-check on every request.\n\n"
        f"---\n\n"
    )


def resolve_base_url(request: Optional[Request]) -> str:
    """Return the externally-reachable ``{origin}/api/v1`` base URL."""
    cors = settings.CORS_ORIGINS
    if cors:
        origin = cors[0].rstrip("/")
    elif request is not None:
        fwd_host = request.headers.get("x-forwarded-host")
        if fwd_host:
            scheme = request.headers.get("x-forwarded-proto", "https")
            origin = f"{scheme}://{fwd_host}"
        else:
            host_hdr = request.headers.get("host", "localhost:3000")
            scheme = request.url.scheme
            origin = f"{scheme}://{host_hdr}"
    else:
        origin = "https://localhost:3000"
    return f"{origin}/api/v1"


def _feedback_section(base_url: str) -> str:
    """Standard feedback-request block appended to the session prompt.

    v2.339.0 — written for the unified session: ``source`` names the kind of
    work the session did, the phase ids are optional (the session itself is
    attributed from the key), and the MCP tool is named so an MCP-connected
    agent has a way to comply without curl.
    """
    return (
        f"\n---\n\n"
        f"## Feedback — file it when the friction happens\n\n"
        f"**The trigger is an event, not the end of the session.** The moment you "
        f"retry a call, guess at a field, work around a tool, or go back to the "
        f"guide to make something work, file a short critique right then: over "
        f"MCP **`submit_feedback`**, over curl `POST {base_url}/agent/feedback`. "
        f"One line per item is enough, and several submissions during a session "
        f"are the norm. Most sessions never reach a tidy ending — the terminal "
        f"closes, the operator moves on — so feedback saved for the end is "
        f"feedback that is never filed.\n\n"
        f"**Checkpoints, if you filed nothing along the way:** "
        f"`execution-sessions/{{id}}/complete` answers with "
        f"`feedback_recorded`; when it is `false`, file before you go on. The "
        f"session end is the last resort, not the plan.\n\n"
        f"**Who reads it:** a coding agent working on BlueStick itself, looking for "
        f"things to fix or build. Write for that reader: name the endpoint or tool, "
        f"say what you expected and what actually happened, include the exact error "
        f"text or the field that was missing, and say what would have let you finish "
        f"faster. \"The API was fine\" is not useful; \"`assist_list_hosts` gives a page "
        f"with no total, so I answered a count from one page until I found "
        f"`assist_count_hosts`\" is.\n\n"
        f"Your session is attributed from your key; `source` says what kind of work "
        f"the feedback is about — `assist` for queries and notes only, "
        f"`reconnaissance` (scanning and uploading), `plan_generation` (add "
        f"`test_plan_id`), or `in_session_execution` (add `execution_session_id`). "
        f"A session that did several kinds may submit one per kind.\n\n"
        f"```json\n"
        f"{{\n"
        f'  "source": "assist | reconnaissance | plan_generation | in_session_execution",\n'
        f'  "prompt_version": "{PROMPT_VERSION}",\n'
        f'  "test_plan_id": null, "execution_session_id": null,\n'
        f'  "overall_rating": 1-5,\n'
        f'  "api_critiques": [\n'
        f'    {{"endpoint": "/agent/... or tool name", "issue": "expected X, got Y — exact error/field", "suggestion": "the change that would have removed this"}}\n'
        f"  ],\n"
        f'  "tool_suggestions": [\n'
        f'    // CLI binaries only (e.g. "naabu", "nuclei", "subfinder").\n'
        f'    {{"name": "binary-name", "category": "recon|enum|exploit|post|reporting", "rationale": "what this binary does that the catalog is missing"}}\n'
        f"  ],\n"
        f'  "friction_notes": "Where you guessed, retried, re-read the guide, or worked around something — one line each, with the tool/endpoint named.",\n'
        f'  "agent_metrics": {{\n'
        f'    "agent_name": "claude-code|codex|chatgpt|other",\n'
        f'    "model": "model id if known",\n'
        f'    "tool_calls_total": 0,\n'
        f'    "notes": "cost estimate, rate-limit hits, compactions, etc."\n'
        f"  }}\n"
        f"}}\n"
        f"```\n\n"
        f"**Metrics guidance:** report any `agent_metrics` fields you can access; "
        f"omit anything your environment does not expose.\n"
    )


def _integration_block(integrations: list) -> str:
    """Render decrypted scanner-integration credentials as a prompt section.

    Security boundary (enforced, not assumed): the frontend ``InAppAgentPanel``
    MUST call ``sanitizePromptForLlm`` before POSTing any prompt derived from
    this block to a hosted LLM.  Changing the ``  - <Label>:`` bullet shape
    without updating ``promptSanitizer.ts`` WILL leak secrets — keep them in
    sync.  The copy-paste flow intentionally keeps plaintext (the user pasting
    it authorized the exposure by creating the integration).
    """
    if not integrations:
        return (
            "\n### Credentialed scanners\n"
            "No scanner integrations are configured for this project. If a "
            "vulnerability scanner, template runner, or web-app scanner would "
            "help, ask the user to configure one at **Scanner Integrations** in "
            "the sidebar, and upload its output to `POST /agent/uploads` like any "
            "other scanner.\n"
        )
    lines = ["\n### Credentialed scanners\n"]
    lines.append(
        "The user has configured these scanner credentials. Use them **only** "
        "against in-scope targets, and always show the exact invocation to the "
        "user before running it.\n"
    )
    for i in integrations:
        itype = i.get("integration_type", "generic_api")
        name = i.get("name") or "(unnamed)"
        base = i.get("base_url") or "(no base URL)"
        if itype == "nessus":
            extra = i.get("extra_config") or {}
            max_hosts = extra.get("max_hosts_per_scan") if isinstance(extra, dict) else None
            chunking_note = (
                f"    **License cap**: `max_hosts_per_scan = {max_hosts}`. Split "
                f"larger chunks into sequential scans of {max_hosts} hosts.\n"
                if max_hosts else
                "    **License cap**: none configured. If Nessus refuses a scan "
                "past a size, ask the operator for the per-scan host limit and chunk to it.\n"
            )
            lines.append(
                f"- **Nessus — `{name}`**\n"
                f"  - URL: `{base}`\n"
                f"  - Access key: `{i.get('secret') or '(missing)'}`\n"
                f"  - Secret key: `{i.get('secret2') or '(missing)'}`\n"
                f"  - Guidance: launch a policy scan via the Nessus REST API against the "
                f"    target list, poll for completion, pull the .nessus/CSV report, and "
                f"    upload it.\n"
                f"{chunking_note}"
            )
        elif itype == "openvas":
            gmp_port = (i.get("extra_config") or {}).get("gmp_port", 9390) if isinstance(i.get("extra_config"), dict) else 9390
            lines.append(
                f"- **OpenVAS / Greenbone — `{name}`**\n"
                f"  - URL: `{base}` · GMP port: `{gmp_port}`\n"
                f"  - Username: `{i.get('secret') or '(missing)'}`\n"
                f"  - Password: `{i.get('secret2') or '(missing)'}`\n"
                f"  - Guidance: use `gvm-cli` / `gvm-tools` over GMP to create a "
                f"    target + task against in-scope subnets, start it, poll, then export "
                f"    the XML report and upload it. The GSA web URL cannot drive scans; GMP can.\n"
            )
        elif itype == "nuclei":
            lines.append(
                f"- **Nuclei — `{name}`**\n"
                f"  - PDCP token: `{i.get('secret') or '(not set)'}`\n"
                f"  - Guidance: run nuclei against identified web services; "
                f"`-severity critical,high` for an initial pass.\n"
            )
        elif itype == "burp":
            lines.append(
                f"- **Burp — `{name}`**\n"
                f"  - URL: `{base}`\n"
                f"  - API key: `{i.get('secret') or '(missing)'}`\n"
                f"  - Guidance: use the Burp Enterprise / Professional REST API against "
                f"    discovered web targets.\n"
            )
        else:
            lines.append(
                f"- **{itype} — `{name}`**\n"
                f"  - URL: `{base}`\n"
                f"  - Secret: `{i.get('secret') or '(not set)'}`\n"
                f"  - Guidance: ask the user for the exact invocation if it isn't obvious.\n"
            )
    lines.append(
        "\nUpload scanner output (`POST /agent/uploads`) so it lands in the same "
        "hosts/ports/findings tables as everything else; don't dump raw output "
        "into notes.\n"
    )
    return "".join(lines)


def build_session_instructions(
    *,
    request: Optional[Request],
    session_id: int,
    project_id: int,
    project_name: str,
    purpose: Optional[str],
    raw_api_key: str,
    user_label: str,
    user_id: Optional[int],
    integrations: Optional[list] = None,
    resumed: bool = False,
) -> str:
    """The session-start prompt for a unified project agent session.

    One prompt for the whole session.  It orients the agent, states the
    session-level rules (which it reads back before acting), and points at
    the guide for the operational detail.  Execution runs are optional
    groupings that return their own read-back when opened; there are no
    recon runs (v2.433.1).
    """
    from datetime import datetime, timezone
    base_url = resolve_base_url(request)
    guide_url = f"{base_url}/agents-guide"

    provenance = build_provenance_block(
        base_url=base_url,
        user_label=user_label,
        user_id=user_id,
        action="agent session",
        target_label=f"project #{project_id} ({project_name}); agent session #{session_id}",
        timestamp_iso=datetime.now(timezone.utc).isoformat(),
    )

    resume_notice = ""
    if resumed:
        resume_notice = (
            "> **⟳ RESUMED SESSION.** This session was resumed with a fresh key; "
            "the previous key is revoked. A prior agent process worked this "
            "session and may have died mid-command — check the working directory "
            "for output files it left behind and upload any that never landed "
            "before running anything again. Any execution runs it had open are "
            "listed under `open_phases` on `GET /agent/identity` — read their "
            "progress before continuing "
            "(`/agent/test-plans/{plan_id}/execution-context`) so you continue "
            "coverage rather than "
            "repeating it.\n\n"
        )

    purpose_line = (
        f"**The operator stated this purpose:** {purpose.strip()}\n\n"
        if purpose and purpose.strip() else ""
    )

    instructions = (
        provenance +
        resume_notice +
        f"## Agent Session — project {project_name} (id {project_id})\n\n"
        f"You act as **{user_label}** in one BlueStick project, and they drive: "
        f"work on what they ask, and propose next steps rather than taking them "
        f"unasked. You can do anything {user_label} may do in this project — a "
        f"write that returns 403 means their project role does not permit it, "
        f"which is the guardrail working, not an error to route around.\n\n"
        + render_read_back("project") + "\n"
        + render_safety_rules() + "\n"
        + purpose_line
        + f"**Base URL:** {base_url}/agent · **Prompt version:** {PROMPT_VERSION}\n"
        f"**Auth header (every request):** `X-API-Key: {raw_api_key}`\n"
        f"Certificate: BlueStick's is issued by the operator's local root CA, so "
        f"use `curl -s` — never `-k`, which accepts any server claiming this "
        f"address. If curl reports a certificate error, tell the operator: the "
        f"root is not trusted on this machine yet (`ca/local-ca.sh trust-help`), "
        f"or the deployment is still self-signed; add `-k` only if they say to. "
        f"In PowerShell use `curl.exe` "
        f"(bare `curl` is an `Invoke-WebRequest` alias). If curl is blocked by your "
        f"sandbox, ask the user to run it.\n\n"
        + render_key_expiry_guidance() + "\n"
        f"### The guide is reference\n\n"
        f"```\n"
        f"curl -s '{guide_url}?workflow=<what you are doing>'\n"
        f"```\n\n"
        f"The guide holds the field shapes, body formats, upload formats and "
        f"endpoint details — read the part you need when something here leaves "
        f"you guessing, not all of it up front. Fetch the slice for what you are doing "
        f"(`reconnaissance`, `plan_generation`, `execution`, or `assist` for "
        f"queries and notes); omit `workflow` for the whole thing.\n\n"
        f"**Say which model you are.** Pass `agent_model` (the model you are "
        f"running as, e.g. `claude-opus-5-5`) when you register a plan, open an "
        f"execution run, record evidence, propose a change or end the session — "
        f"it labels that work, so the "
        f"operator can tell which model produced what. Your client is recorded "
        f"from the MCP handshake; there is nothing else to report.\n\n"
        f"### What you can do — in whatever order the work needs\n"
        f"- **Answer questions / write a report.** Query the inventory read-only "
        f"via the `/agent/assist/*` reads — `GET /agent/assist/context`, "
        f"`/agent/assist/hosts`, `/agent/assist/hosts/{{id}}`, "
        f"`/agent/assist/findings`, `/agent/assist/posture`, "
        f"`/agent/assist/patterns`, and the bulk `*.ndjson` downloads for report "
        f"material. Guide § assist.\n"
        f"- **Record what you found about a host.** `POST /agent/hosts/{{id}}/notes`, "
        f"`POST /agent/hosts/{{id}}/follow` (review status), "
        f"`PATCH /agent/hosts/{{id}}` (correct hostname/OS). Notes carry "
        f"{user_label}'s name and an agent badge — cite the host/port/finding, "
        f"and never mark a host `reviewed` on your own initiative.\n"
        f"- **Record what you ran; propose what it means.** `POST /agent/evidence` "
        f"records a command you ran against a host and what came back (tool, "
        f"command, outcome, summary, raw output) — no plan needed. A change to "
        f"what the team has concluded is a PROPOSAL {user_label} or a colleague "
        f"accepts or rejects: report text for a finding "
        f"(`POST /agent/proposals/finding-text`), a new finding "
        f"(`/agent/proposals/finding`), promoting or dismissing a scanner "
        f"observation (`/agent/proposals/observation`), an endpoint's status "
        f"(`/agent/proposals/endpoint-status`). Cite your evidence ids; "
        f"`GET /agent/proposals?mine=true` shows what was decided.\n"
        f"- **Scan and upload.** Run scanners locally from the working directory "
        f"and `POST /agent/uploads` (multipart; poll `GET /agent/uploads/{{id}}`) — "
        f"no run needs to be open. `GET /agent/scopes` lists the declared scopes; "
        f"`GET /agent/scopes/{{id}}/subnets` and `/domains` are what is in scope, "
        f"and `/live-hosts.txt`, `/web-targets.txt`, `/hosts.ndjson` are target "
        f"files to feed your scanners. Guide § reconnaissance.\n"
        f"- **Plan and execute tests.** Register a plan (`POST /agent/test-plans` "
        f"`{{\"title\": ...}}`, then `.../entries`) — the record of what you set "
        f"out to test — and work it when ready: `POST /agent/execution-sessions/start` "
        f"`{{\"plan_id\": N}}`, then record each test's command, output and "
        f"finding. Nothing waits on approval. Guide § plan_generation and § "
        f"execution.\n\n"
        f"### Long-running commands — never block a single tool call on one\n"
        f"Your client has its own tool timeout, and a scan that outlives it ends "
        f"your process while the scan keeps running: the output is orphaned, any "
        f"open run never gets its `/complete`, and the operator sees a session that "
        f"looks alive but isn't. Run anything that may take more than a minute "
        f"or two in the background from the working directory, capture its PID "
        f"at launch, and poll that PID (guide § Working directory). Upload each "
        f"output file as it finishes; do not hold results for one upload at the "
        f"end.\n\n"
        f"### Last — end the session when the operator says so (MANDATORY)\n"
        f"End the session only when the operator tells you they are finished. "
        f"Finishing a task is not that: report what you did and wait for the "
        f"next instruction. A session opened with no task yet is waiting for "
        f"one, not done — after the setup steps, say you are ready and wait. "
        f"When the operator says they are finished: close every execution run you opened "
        f"(`POST /agent/execution-sessions/{{id}}/complete`); if you have filed "
        f"no feedback yet in this session, file it now (below); then "
        f"`POST {base_url}/agent/session/end` (MCP `end_session`) "
        f"with a line of `notes`. It revokes your key and marks the session "
        f"ended; nothing you call afterwards will authenticate, so it is the last "
        f"call. A session that is never ended shows as running on the operator's "
        f"Agent Activity page until it lapses days later. If it refuses with 409 "
        f"it names the runs still open — complete them and call it again.\n"
        f"\n**Session:** #{session_id} · **Project:** {project_name}\n"
    )

    instructions += _integration_block(integrations or [])
    instructions += _feedback_section(base_url=base_url)
    return instructions
