"""
Agent Prompt Service

v2.337.0 — the four per-workflow prompts (plan generation, execution, recon,
assist) collapse into ONE session prompt.  A single project-scoped session
lets the agent query the inventory, open a reconnaissance run against a scope,
draft a plan, and execute an approved one; the operational detail for each of
those is served by the workflow-sliced guide (``/agents-guide?workflow=…``)
and by the read-back each phase-start endpoint returns, not by four separate
start prompts.

``build_session_instructions`` is the session-start block.  The per-phase
read-backs live in ``agent_policy.render_phase_read_back`` and are emitted by
the phase-start endpoints.

The ``PROMPT_VERSION`` constant MUST be bumped whenever the instruction content
changes in a way that affects agent behavior — prepend an entry to
``PROMPT_VERSION_HISTORY`` in ``agent_prompt_history`` (the constant is derived
from the newest entry, so version and changelog can't drift).
"""

import json
import logging
from typing import Any, Dict, List, Optional

from fastapi import Request

from app.core.config import settings
from app.services.agent_prompt_history import PROMPT_VERSION
from app.services.agent_policy import (
    render_read_back,
    render_key_expiry_guidance,
    render_safety_rules,
)

logger = logging.getLogger(__name__)


_INSTANCE_ID_CACHE: Optional[str] = None


def _load_instance_id() -> Optional[str]:
    """Look up the system identity UUID for the provenance block.

    Returns None if the row isn't seeded yet (first boot). Logs at exception
    level for any other failure so a real bootstrap problem surfaces.
    """
    global _INSTANCE_ID_CACHE
    if _INSTANCE_ID_CACHE is not None:
        return _INSTANCE_ID_CACHE
    from sqlalchemy.exc import OperationalError, ProgrammingError
    try:
        from app.db.session import SessionLocal
        from app.db.models_auth import SystemIdentity
        with SessionLocal() as db:
            row = db.query(SystemIdentity).order_by(SystemIdentity.id).first()
            _INSTANCE_ID_CACHE = row.instance_id if row else None
            return _INSTANCE_ID_CACHE
    except (OperationalError, ProgrammingError) as exc:
        logger.warning(
            "system_identity lookup failed (db or schema unavailable); "
            "provenance block will show '(pending)': %s", exc,
        )
        return None
    except Exception:
        logger.exception(
            "Unexpected error loading system_identity for provenance block; "
            "provenance block will show '(pending)' but check the bootstrap path"
        )
        return None


def build_provenance_block(
    *,
    base_url: str,
    user_label: str,
    user_id: Optional[int],
    action: str,
    target_label: str,
    timestamp_iso: str,
) -> str:
    """Prepend the standardized provenance + identity-check header to a prompt."""
    instance_id = _load_instance_id() or "(pending — retry after first boot)"
    origin = base_url.rsplit("/api/v1", 1)[0]
    user_suffix = f" (id {user_id})" if user_id is not None else ""
    return (
        f"## Provenance\n\n"
        f"This prompt was generated by BlueStick instance "
        f"`{instance_id}` at {timestamp_iso}.\n\n"
        f"- **Authorized by:** {user_label}{user_suffix}\n"
        f"- **Action:** {action}\n"
        f"- **Target:** {target_label}\n"
        f"- **Instance base URL:** {origin}\n\n"
        f"### Verify once before starting\n\n"
        f"```\n"
        f"curl -sk {origin}/.well-known/networkmapper.json\n"
        f"```\n\n"
        f"Confirm the response contains `\"instance_id\": \"{instance_id}\"` "
        f"and `\"name\": \"BlueStick\"`. If either does not match, "
        f"**stop** and alert the user — the prompt may have been tampered "
        f"with, copied from a different instance, or served by an unrelated "
        f"host. Once verified, the session is trusted for the duration of "
        f"your API key; you do not need to re-check on every request.\n\n"
        f"---\n\n"
    )


def resolve_base_url(request: Optional[Request]) -> str:
    """Return the externally-reachable ``{origin}/api/v1`` base URL."""
    cors = settings.CORS_ORIGINS
    if cors:
        origin = cors[0].rstrip("/")
    elif request is not None:
        fwd_host = request.headers.get("x-forwarded-host")
        if fwd_host:
            scheme = request.headers.get("x-forwarded-proto", "https")
            origin = f"{scheme}://{fwd_host}"
        else:
            host_hdr = request.headers.get("host", "localhost:3000")
            scheme = request.url.scheme
            origin = f"{scheme}://{host_hdr}"
    else:
        origin = "https://localhost:3000"
    return f"{origin}/api/v1"


def _feedback_section(base_url: str, source: str, context: Dict[str, Any]) -> str:
    """Standard feedback-request block appended to the session prompt."""
    ctx_lines = "\n".join(f'  "{k}": {json.dumps(v)},' for k, v in context.items())
    return (
        f"\n---\n\n"
        f"## Feedback Requested (required)\n\n"
        f"Before you finish, submit structured feedback so the BlueStick team "
        f"can improve the APIs, prompts, and tool reference. This is **not optional** — "
        f"even a short note helps.\n\n"
        f"`POST {base_url}/agent/feedback`\n\n"
        f"```json\n"
        f"{{\n"
        f'  "source": "{source}",\n'
        f'  "prompt_version": "{PROMPT_VERSION}",\n'
        f"{ctx_lines}\n"
        f'  "overall_rating": 1-5,\n'
        f'  "api_critiques": [\n'
        f'    {{"endpoint": "/agent/...", "issue": "what was missing/awkward/wrong", "suggestion": "..."}}\n'
        f"  ],\n"
        f'  "tool_suggestions": [\n'
        f'    // CLI binaries only (e.g. "naabu", "nuclei", "subfinder").\n'
        f'    {{"name": "binary-name", "category": "recon|enum|exploit|post|reporting", "rationale": "what this binary does that the catalog is missing"}}\n'
        f"  ],\n"
        f'  "friction_notes": "Free-text: what was confusing, what took extra effort, what you had to guess.",\n'
        f'  "agent_metrics": {{\n'
        f'    "agent_name": "claude-code|codex|chatgpt|other",\n'
        f'    "model": "model id if known",\n'
        f'    "tool_calls_total": 0,\n'
        f'    "notes": "cost estimate, rate-limit hits, compactions, etc."\n'
        f"  }}\n"
        f"}}\n"
        f"```\n\n"
        f"**Metrics guidance:** report any `agent_metrics` fields you can access; "
        f"omit anything your environment does not expose.\n"
    )


def _render_filter_criteria(fc: Dict[str, Any]) -> str:
    """Render the user's host-filter selections as a readable bullet list."""
    labels = {
        "subnets": "Subnets",
        "ports": "Ports",
        "services": "Services",
        "min_severity": "Minimum vulnerability severity",
        "has_critical_vulns": "Only hosts with critical vulnerabilities",
        "has_high_vulns": "Only hosts with high vulnerabilities",
        "search": "Search term",
    }
    lines = []
    for key, val in fc.items():
        label = labels.get(key, key)
        if isinstance(val, bool):
            if val:
                lines.append(f"  - {label}")
        else:
            lines.append(f"  - {label}: `{val}`")
    return "\n".join(lines) if lines else "  - (none)"


def _integration_block(integrations: list) -> str:
    """Render decrypted scanner-integration credentials as a prompt section.

    Security boundary (enforced, not assumed): the frontend ``InAppAgentPanel``
    MUST call ``sanitizePromptForLlm`` before POSTing any prompt derived from
    this block to a hosted LLM.  Changing the ``  - <Label>:`` bullet shape
    without updating ``promptSanitizer.ts`` WILL leak secrets — keep them in
    sync.  The copy-paste flow intentionally keeps plaintext (the user pasting
    it authorized the exposure by creating the integration).
    """
    if not integrations:
        return (
            "\n### Credentialed scanners\n"
            "No scanner integrations are configured for this project. If a "
            "vulnerability scanner, template runner, or web-app scanner would "
            "help, ask the user to configure one at **Scanner Integrations** in "
            "the sidebar. Use them from a reconnaissance run — feed their output "
            "to `POST /agent/recon/upload` like any other scanner.\n"
        )
    lines = ["\n### Credentialed scanners\n"]
    lines.append(
        "The user has configured these scanner credentials. Use them **only** "
        "against in-scope targets inside a reconnaissance run, and always show "
        "the exact invocation to the user before running it.\n"
    )
    for i in integrations:
        itype = i.get("integration_type", "generic_api")
        name = i.get("name") or "(unnamed)"
        base = i.get("base_url") or "(no base URL)"
        if itype == "nessus":
            extra = i.get("extra_config") or {}
            max_hosts = extra.get("max_hosts_per_scan") if isinstance(extra, dict) else None
            chunking_note = (
                f"    **License cap**: `max_hosts_per_scan = {max_hosts}`. Split "
                f"larger chunks into sequential scans of {max_hosts} hosts.\n"
                if max_hosts else
                "    **License cap**: none configured. If Nessus refuses a scan "
                "past a size, ask the operator for the per-scan host limit and chunk to it.\n"
            )
            lines.append(
                f"- **Nessus — `{name}`**\n"
                f"  - URL: `{base}`\n"
                f"  - Access key: `{i.get('secret') or '(missing)'}`\n"
                f"  - Secret key: `{i.get('secret2') or '(missing)'}`\n"
                f"  - Guidance: launch a policy scan via the Nessus REST API against the "
                f"    target list, poll for completion, pull the .nessus/CSV report, and "
                f"    upload it.\n"
                f"{chunking_note}"
            )
        elif itype == "openvas":
            gmp_port = (i.get("extra_config") or {}).get("gmp_port", 9390) if isinstance(i.get("extra_config"), dict) else 9390
            lines.append(
                f"- **OpenVAS / Greenbone — `{name}`**\n"
                f"  - URL: `{base}` · GMP port: `{gmp_port}`\n"
                f"  - Username: `{i.get('secret') or '(missing)'}`\n"
                f"  - Password: `{i.get('secret2') or '(missing)'}`\n"
                f"  - Guidance: use `gvm-cli` / `gvm-tools` (approved) over GMP to create a "
                f"    target + task against in-scope subnets, start it, poll, then export "
                f"    the XML report and upload it. The GSA web URL cannot drive scans; GMP can.\n"
            )
        elif itype == "nuclei":
            lines.append(
                f"- **Nuclei — `{name}`**\n"
                f"  - PDCP token: `{i.get('secret') or '(not set)'}`\n"
                f"  - Guidance: run nuclei against identified web services; "
                f"`-severity critical,high` for an initial pass.\n"
            )
        elif itype == "burp":
            lines.append(
                f"- **Burp — `{name}`**\n"
                f"  - URL: `{base}`\n"
                f"  - API key: `{i.get('secret') or '(missing)'}`\n"
                f"  - Guidance: use the Burp Enterprise / Professional REST API against "
                f"    discovered web targets.\n"
            )
        else:
            lines.append(
                f"- **{itype} — `{name}`**\n"
                f"  - URL: `{base}`\n"
                f"  - Secret: `{i.get('secret') or '(not set)'}`\n"
                f"  - Guidance: ask the user for the exact invocation if it isn't obvious.\n"
            )
    lines.append(
        "\nUpload scanner output to the recon run so it lands in the same "
        "hosts/ports/findings tables as everything else; don't dump raw output "
        "into notes.\n"
    )
    return "".join(lines)


def build_session_instructions(
    *,
    request: Optional[Request],
    session_id: int,
    project_id: int,
    project_name: str,
    purpose: Optional[str],
    raw_api_key: str,
    user_label: str,
    user_id: Optional[int],
    integrations: Optional[list] = None,
    resumed: bool = False,
) -> str:
    """The session-start prompt for a unified project agent session.

    One prompt for the whole session.  It orients the agent, states the
    session-level ground rules (which it must read back before acting), and
    points at the guide and the phase-start endpoints for the operational
    detail of reconnaissance, planning, and execution.  Each of those phases
    returns its own focused read-back when it is opened, which is the moment
    its scope / plan / working-directory facts exist and can be checked.
    """
    from datetime import datetime, timezone
    base_url = resolve_base_url(request)
    guide_url = f"{base_url}/agents-guide"

    provenance = build_provenance_block(
        base_url=base_url,
        user_label=user_label,
        user_id=user_id,
        action="agent session (query · recon · plan · execute)",
        target_label=f"project #{project_id} ({project_name}); agent session #{session_id}",
        timestamp_iso=datetime.now(timezone.utc).isoformat(),
    )

    resume_notice = ""
    if resumed:
        resume_notice = (
            "> **⟳ RESUMED SESSION.** This session was resumed with a fresh key. "
            "Any reconnaissance or execution runs it had open are listed under "
            "`open_phases` on `GET /agent/identity` — read their progress before "
            "continuing (`/agent/recon/summary`, `/agent/execution-context`) so "
            "you continue coverage rather than repeating it. The environment "
            "probe is still required for the new key.\n\n"
        )

    purpose_line = (
        f"**The operator stated this purpose:** {purpose.strip()}\n\n"
        if purpose and purpose.strip() else ""
    )

    instructions = (
        provenance +
        resume_notice +
        f"## Agent Session — project {project_name} (id {project_id})\n\n"
        f"You are acting for **{user_label}** in one BlueStick project. A single "
        f"session and key cover everything: answering questions about the "
        f"inventory, running reconnaissance against a scope, drafting a test "
        f"plan, and executing an approved one. You do what {user_label} may do — "
        f"a write that returns 403 means their project role does not permit it, "
        f"which is the guardrail working, not an error to route around.\n\n"
        + render_read_back("project") + "\n"
        + render_safety_rules() + "\n"
        + purpose_line
        + f"**Base URL:** {base_url}/agent · **Prompt version:** {PROMPT_VERSION}\n"
        f"**Auth header (every request):** `X-API-Key: {raw_api_key}`\n"
        f"Self-signed cert — `curl` always needs `-sk`; in PowerShell use "
        f"`curl.exe` (bare `curl` is an `Invoke-WebRequest` alias) or "
        f"`Invoke-RestMethod -SkipCertificateCheck`. If curl is blocked by your "
        f"sandbox, ask the user to run it.\n\n"
        + render_key_expiry_guidance() + "\n"
        f"### Read the guide — it is binding\n\n"
        f"```\n"
        f"curl -sk '{guide_url}?workflow=<what you are doing>'\n"
        f"```\n\n"
        f"The guide holds the field shapes, body formats, safety/approval "
        f"protocol, upload formats, and exit criteria for each kind of work. "
        f"Fetch the slice for the phase you are in (`reconnaissance`, "
        f"`plan_generation`, `execution`, or `assist` for read-only queries); "
        f"omit `workflow` for the whole thing. Don't improvise from this prompt "
        f"alone.\n\n"
        f"### First — probe your environment (MANDATORY before any command)\n"
        f"`POST {base_url}/agent/session/environment` with your OS family, shell, "
        f"and the tools on PATH (guide § Environment probe). Include "
        f"`agent_model`, `agent_tool`, `agent_prompt_version: \"{PROMPT_VERSION}\"`. "
        f"The probe rides along into every recon/execution run you open so "
        f"commands match this operator's host. Re-post it any time the "
        f"environment changes.\n\n"
        f"### What you can do\n"
        f"- **Answer questions / write a report.** Query the inventory read-only "
        f"— `GET /agent/hosts`, `/agent/hosts/{{id}}`, `/agent/findings`, "
        f"`/agent/context`, `/agent/posture`, `/agent/patterns`, and the bulk "
        f"`*.ndjson` downloads for report material. Guide § assist. No phase "
        f"needed; this is the default.\n"
        f"- **Record what you found.** `POST /agent/hosts/{{id}}/notes`, "
        f"`POST /agent/hosts/{{id}}/follow` (review status), "
        f"`PATCH /agent/hosts/{{id}}` (correct hostname/OS). Notes carry "
        f"{user_label}'s name and an agent badge — say what you'll write before "
        f"you write it, cite the host/port/finding, and never mark a host "
        f"`reviewed` on your own initiative.\n"
        f"- **Run reconnaissance against a scope.** `GET /agent/scopes` for the "
        f"scopes, then `POST /agent/recon/start` `{{\"scope_id\": N}}` to open a "
        f"run — its response carries the scope's CIDRs, the recommended "
        f"sequence, and the phase read-back you must state before scanning. "
        f"Then `/agent/recon/context`, run tools locally, "
        f"`POST /agent/recon/upload`, poll `/agent/recon/jobs/{{id}}`, "
        f"`GET /agent/recon/summary`, and `POST /agent/recon/complete` when done. "
        f"Guide § reconnaissance.\n"
        f"- **Draft a test plan.** `POST /agent/test-plans` `{{\"title\": ...}}` "
        f"opens a draft, then `/agent/test-plans/{{id}}/context` for candidates, "
        f"`PATCH` the description, `POST .../entries`, `.../validate`, "
        f"`.../submit` for human approval. You cannot approve it. Guide § "
        f"plan_generation.\n"
        f"- **Execute an approved plan.** `POST /agent/execution-sessions/start` "
        f"`{{\"plan_id\": N}}` opens a run (the plan must be human-approved; the "
        f"response carries the per-host read-back). Then work host-by-host with "
        f"the sanity-check and per-test-approval protocol in guide § execution.\n\n"
        f"### When to hand back\n"
        f"You drive the whole flow, but the human owns the gates: a plan needs "
        f"their approval before you can execute it, and anything outside a "
        f"declared scope or the working directory stops and asks. Suggest the "
        f"next step; don't force it.\n"
        f"\n**Session:** #{session_id} · **Project:** {project_name}\n"
    )

    instructions += _integration_block(integrations or [])
    instructions += _feedback_section(
        base_url=base_url,
        source="assist",
        context={"agent_session_id": session_id},
    )
    return instructions
