"""
Test Plan Export Bundle Service

Packages an approved test plan into a portable ZIP bundle that a remote
agent can execute offline.  The bundle freezes a snapshot of the plan +
host context at export time; results come back via the import-results
endpoint and are correlated to the original execution session by
``bundle_id``.

Bundle layout:

    manifest.json       — bundle_id, plan_id, project_id, versions, timestamps
    plan.json           — plan metadata + per-host context (snapshot)
    instructions.md     — same markdown the /execute endpoint emits, minus
                          the API key block (offline bundles have no key)
    results_schema.json — JSON Schema for the results file the agent
                          should produce and hand back for import

The schema is deliberately small and documented; it's the contract the
import parser validates against.

Commit-boundary policy (audit #43):
    ``build_export_bundle`` **does not commit**.  It calls ``db.flush()``
    where it needs an autogenerated PK for the manifest, and leaves the
    caller to decide the transaction boundary.  This is the minority
    position among BlueStick services (most commit internally) but
    it's the right choice here because the endpoint that calls this
    wraps the export in a larger transaction that also transitions the
    plan status, appends an audit row, and returns the zip to the
    client — all of which must roll back together if anything fails.
"""

from __future__ import annotations

import hashlib
import io
import json
import secrets
import zipfile
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from fastapi import Request
from sqlalchemy.orm import Session

from app.db.models_agent import (
    TestPlan, TestPlanEntry, ExecutionSession,
    ExecutionSessionStatus, ExecutionSessionMode,
)
from app.services.agent_prompt_service import (
    PROMPT_VERSION, resolve_base_url,
)
from app.services.agent_policy import render_safety_rules


# JSON Schema (draft-07) for the results file a remote agent produces.
# Kept intentionally small — only the fields the importer actually uses.
# Agents should omit unknown fields rather than guess.
RESULTS_SCHEMA: Dict[str, Any] = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "BlueStick Remote Execution Results",
    "type": "object",
    "required": ["bundle_id", "plan_id", "execution_session_id", "results"],
    "properties": {
        "bundle_id": {
            "type": "string",
            "description": "Copy verbatim from manifest.json. Used to correlate with the execution session."
        },
        "plan_id": {"type": "integer"},
        "execution_session_id": {"type": "integer"},
        "is_final": {
            "type": "boolean",
            "description": "True when you have no more results to submit. Sets session status to completed."
        },
        "sanity_checks": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["entry_id", "method", "target_ip", "passed"],
                "properties": {
                    "entry_id": {"type": "integer"},
                    "method": {
                        "type": "string",
                        "enum": ["banner_grab", "reverse_dns", "ping", "network_context"]
                    },
                    "target_ip": {"type": "string"},
                    "port_checked": {"type": ["integer", "null"]},
                    "expected_value": {"type": ["string", "null"]},
                    "actual_value": {"type": ["string", "null"]},
                    "source_ip": {"type": ["string", "null"]},
                    "dns_result": {"type": ["string", "null"]},
                    "passed": {"type": "boolean"},
                    "details": {"type": ["string", "null"]}
                }
            }
        },
        "results": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["entry_id", "test_index", "status"],
                "properties": {
                    "entry_id": {"type": "integer"},
                    "test_index": {
                        "type": "integer",
                        "description": "Zero-based index into the entry's proposed_tests array."
                    },
                    "status": {
                        "type": "string",
                        "enum": ["executed", "skipped", "failed", "not_applicable", "pending"]
                    },
                    "command_run": {"type": ["string", "null"]},
                    "raw_output": {
                        "type": ["string", "null"],
                        "description": "Will be truncated server-side to TEST_OUTPUT_MAX_BYTES (default 100KB)."
                    },
                    "findings_summary": {"type": ["string", "null"]},
                    "severity": {
                        "type": ["string", "null"],
                        "enum": ["critical", "high", "medium", "low", "info", "none", None]
                    },
                    "is_finding": {"type": "boolean"},
                    "executed_at": {
                        "type": ["string", "null"],
                        "description": "ISO 8601 timestamp."
                    }
                }
            }
        },
        "feedback": {
            "type": ["object", "null"],
            "description": "Optional structured feedback; mirrors the POST /agent/feedback payload.",
            "properties": {
                "source": {"type": "string"},
                "prompt_version": {"type": "string"},
                "overall_rating": {"type": ["integer", "null"]},
                "api_critiques": {"type": "array"},
                "tool_suggestions": {"type": "array"},
                "friction_notes": {"type": ["string", "null"]},
                "agent_metrics": {"type": ["object", "null"]}
            }
        }
    }
}


def _build_offline_instructions(
    *,
    request: Optional[Request],
    plan_id: int,
    plan_title: str,
    session_id: int,
    bundle_id: str,
    entry_count: int,
) -> str:
    """Bundle instructions (mirror of build_execution_instructions, offline-mode).

    The live-execution instructions assume an API key + reachable /agent/
    endpoints.  This offline variant tells the agent to write results to
    a ``results.json`` file conforming to ``results_schema.json`` and
    hand the file back for import.  No API key is minted; the human
    operator uploads the file via the BlueStick UI.
    """
    base_url = resolve_base_url(request)
    schema_hint = (
        f"See `results_schema.json` in this bundle — every field's purpose, "
        f"allowed values, and optionality are documented there."
    )
    return (
        f"## Agent Remote Execution Instructions (offline bundle)\n\n"
        f"You are executing tests from a BlueStick test plan that was "
        f"exported as a **portable bundle**. No live API connection to "
        f"BlueStick is required. You will write results to a JSON file "
        f"and return it to the operator for offline import.\n\n"
        f"**Bundle ID:** `{bundle_id}`\n"
        f"**Plan:** {plan_title} (id {plan_id})\n"
        f"**Session ID:** {session_id}\n"
        f"**Entries:** {entry_count} host(s) to test\n"
        f"**Prompt version:** {PROMPT_VERSION}\n\n"
        + render_safety_rules() + "\n"
        + f"### Step 1 — Load the bundle\n"
        f"Read `plan.json` to get the list of hosts and proposed tests for each. "
        f"Each entry has a stable `entry_id` and a zero-based `test_index` into "
        f"`proposed_tests` — use those two fields to correlate results.\n\n"
        f"### Step 2 — For each host (in priority order)\n\n"
        f"#### 2a. Sanity check (record in `sanity_checks[]`)\n"
        f"Verify the target before testing:\n"
        f"- Report your source IP, gateway, and DNS resolver.\n"
        f"- `dig -x {{ip}}` and compare to expected hostname.\n"
        f"- Banner-grab a known-open port from context.\n"
        f"- If any check fails, STOP and ask the operator.\n\n"
        f"#### 2b. Execute tests (one at a time, with approval; record in `results[]`)\n"
        f"For each test in the entry's `proposed_tests`:\n"
        f"1. Present the command, wait for user approval.\n"
        f"2. Run it (or ask the user to run it and paste output).\n"
        f"3. Append to `results[]` with `entry_id`, `test_index`, `status`, "
        f"   `command_run`, `raw_output`, `findings_summary`, `severity`, `is_finding`.\n\n"
        f"### Step 3 — Write the results file\n"
        f"Produce `results.json` matching the schema in `results_schema.json`. "
        f"{schema_hint}\n"
        f"Set `is_final: true` when you have nothing more to submit — this tells "
        f"the server to mark the execution session as completed. Interim submissions "
        f"(where you're handing back partial work) should leave `is_final: false`.\n\n"
        f"### Step 4 — Hand off\n"
        f"Give `results.json` back to the operator. They will upload it via "
        f"`POST {base_url}/test-plans/{plan_id}/import-results` (or the "
        f'"Import Results" button on the test plan detail page in the UI).\n\n'
        f"**Remember:** `bundle_id` in your `results.json` MUST match the value "
        f"in `manifest.json` exactly — that's how BlueStick verifies the "
        f"results belong to this session.\n"
        f"\n---\n\n"
        f"## Feedback Requested (required)\n\n"
        f"Include a `feedback` object in `results.json`. It mirrors the live "
        f"`POST /agent/feedback` payload; BlueStick extracts it during import "
        f"so your critiques and tool suggestions land in the same developer "
        f"feedback queue as live-session feedback.\n\n"
        f"Required fields: `source: \"exported_execution\"`, `prompt_version: "
        f"\"{PROMPT_VERSION}\"`, `overall_rating` (1-5), `api_critiques[]`, "
        f"`tool_suggestions[]`, `friction_notes`, and `agent_metrics` "
        f"(agent_name, model, context_window_tokens, context_used_tokens, "
        f"input/output tokens, tool_calls_total, wall_clock_seconds, free-text "
        f"notes). Report whatever metrics you can access — omit the rest.\n"
    )


def build_export_bundle(
    *,
    db: Session,
    request: Optional[Request],
    plan: TestPlan,
    started_by_id: int,
    agent_id: Optional[int],
) -> Dict[str, Any]:
    """Create a new exported execution session and package a ZIP bundle.

    Returns a dict with the ZIP bytes, filename, and bundle_id.  The
    caller commits the DB transaction after writing audit state.

    Raises ``ValueError`` if the plan is empty or in the wrong state.
    """
    if plan.status not in ("approved", "in_progress"):
        raise ValueError(
            f"Cannot export a plan in {plan.status} status — approve it first."
        )

    entries = (
        db.query(TestPlanEntry)
        .filter(TestPlanEntry.test_plan_id == plan.id)
        .all()
    )
    if not entries:
        raise ValueError("Cannot export an empty test plan.")

    # Pause any existing active session.  Same rule as /execute: at most
    # one active session per plan.  An exported bundle is still an active
    # execution — the agent is working offline, but the server considers
    # the session in-flight until results are imported.
    db.query(ExecutionSession).filter(
        ExecutionSession.test_plan_id == plan.id,
        ExecutionSession.status == ExecutionSessionStatus.ACTIVE.value,
    ).update(
        {"status": ExecutionSessionStatus.PAUSED.value},
        synchronize_session=False,
    )

    bundle_id = secrets.token_urlsafe(24)
    session = ExecutionSession(
        test_plan_id=plan.id,
        agent_id=agent_id,
        started_by_id=started_by_id,
        status=ExecutionSessionStatus.ACTIVE.value,
        mode=ExecutionSessionMode.EXPORTED.value,
        bundle_id=bundle_id,
    )
    db.add(session)
    db.flush()  # need session.id for the manifest

    if plan.status == "approved":
        plan.status = "in_progress"

    # --- Build plan.json: frozen snapshot of plan + per-host context ---
    plan_snapshot: Dict[str, Any] = {
        "plan_id": plan.id,
        "version": plan.version,
        "title": plan.title,
        "description": plan.description,
        "project_id": plan.project_id,
        "status_at_export": plan.status,
        "entry_count": len(entries),
        "entries": [],
    }
    for e in entries:
        host = e.host
        plan_snapshot["entries"].append({
            "entry_id": e.id,
            "host_id": e.host_id,
            "host_ip": host.ip_address if host else None,
            "host_hostname": host.hostname if host else None,
            "host_os": getattr(host, "os_name", None) if host else None,
            "priority": e.priority,
            "test_phase": e.test_phase,
            "proposed_tests": e.proposed_tests or [],
            "rationale": e.rationale,
            "notes": e.notes,
        })

    now = datetime.now(timezone.utc)
    manifest: Dict[str, Any] = {
        "bundle_id": bundle_id,
        "schema_version": "1.0",
        "prompt_version": PROMPT_VERSION,
        "plan_id": plan.id,
        "plan_version": plan.version,
        "plan_title": plan.title,
        "project_id": plan.project_id,
        "execution_session_id": session.id,
        "generated_at": now.isoformat(),
        # 30-day soft expiration — the import endpoint ignores this and
        # relies on bundle_id presence, but clients may warn users who
        # are sitting on an old bundle.
        "soft_expires_at": (now + timedelta(days=30)).isoformat(),
        "entry_count": len(entries),
    }

    instructions = _build_offline_instructions(
        request=request,
        plan_id=plan.id,
        plan_title=plan.title,
        session_id=session.id,
        bundle_id=bundle_id,
        entry_count=len(entries),
    )

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest.json", json.dumps(manifest, indent=2, default=str))
        zf.writestr("plan.json", json.dumps(plan_snapshot, indent=2, default=str))
        zf.writestr("instructions.md", instructions)
        zf.writestr("results_schema.json", json.dumps(RESULTS_SCHEMA, indent=2))

    zip_bytes = buf.getvalue()
    filename = (
        f"networkmapper_plan_{plan.id}_v{plan.version}_"
        f"{now.strftime('%Y%m%d_%H%M%S')}.zip"
    )

    return {
        "zip_bytes": zip_bytes,
        "filename": filename,
        "bundle_id": bundle_id,
        "execution_session_id": session.id,
    }
