"""Async report generation — queue service for the report worker.

The heavy export formats (PDF, JSON, markdown-bundle, agent-package) build the
whole document in memory, so they run on a dedicated background worker instead of
the API request thread.  This service is the report-side twin of
``IngestionService``: it owns the ``report_jobs`` queue and reuses the exact same
claim mechanics — ``create_job`` → ``enqueue_job`` (pg_notify) → ``poll_and_run_one``
(``SELECT … FOR UPDATE SKIP LOCKED``) → ``_run_job`` → ``reap_orphaned_jobs`` —
plus a ``cleanup_expired`` pass that deletes artifacts past their TTL.

The generated bytes are written to a shared, worker-writable artifact dir
(``REPORT_STORAGE_DIR``, a sibling of the ingestion queue under uploads) so the
backend's download endpoint can stream the file the worker produced.
"""
from __future__ import annotations

import json
import logging
import os
import shutil
import threading
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

from sqlalchemy import text

from app.core.config import settings
# Imported as a module (not ``from … import SessionLocal``) so tests can rebind
# app.db.session.SessionLocal onto the test engine — mirrors IngestionService.
from app.db import session as _session_module
from app.db.models import ReportJob
from app.db.models_auth import User
from app.services.job_transitions import JobNotTransitionable, JobTransitions

logger = logging.getLogger(__name__)

# The formats that run async on the report worker (CSV + HTML stream synchronously
# on the API and are NOT enqueued here).
# PDF was removed in v2.196.1 — the host-dossier HTML is screen-oriented (gradients,
# sticky, flex, collapsible), so WeasyPrint rendered it slowly (~160s/400 hosts) and
# degraded; the interactive HTML report is the functional handover. Re-adding PDF
# means restoring the "pdf" branch in _render + this tuple + the endpoint pattern.
ASYNC_REPORT_FORMATS = ("json", "agent-package", "markdown-bundle")

_REAP_MAX_RETRIES = 2

# v2.328.0 — shared with IngestionService: one implementation of claim /
# heartbeat / complete / fail / cancel / retry / reap, so the two queues
# can't drift on fencing or locking.
_transitions = JobTransitions(ReportJob, name="report")


class ReportJobService:
    def __init__(self) -> None:
        self._storage_root = Path(settings.REPORT_STORAGE_DIR)

    # --- enqueue side (called from the API request thread) ----------------

    def create_job(
        self, db, *, project_id: int, requested_by_id: Optional[int],
        format: str, report_type: str, filters: Dict[str, Any],
    ) -> ReportJob:
        """Insert a queued report job and return it (the API then calls
        ``enqueue_job`` to wake the worker)."""
        job = ReportJob(
            project_id=project_id,
            requested_by_id=requested_by_id,
            format=format,
            report_type=report_type or "comprehensive",
            filters=filters or {},
            status="queued",
            message="Queued for generation",
        )
        db.add(job)
        db.commit()
        db.refresh(job)
        return job

    def enqueue_job(self, job_id: int) -> None:
        """Best-effort pg_notify so the worker wakes immediately instead of
        waiting for its next poll.  The worker claims queued rows independently
        of this hint, so a failed notify just delays pickup by one poll."""
        db = _session_module.SessionLocal()
        try:
            db.execute(text("SELECT pg_notify('report_jobs', :jid)"), {"jid": str(job_id)})
            db.commit()
        except Exception:
            db.rollback()
            logger.debug("pg_notify for report job %s failed", job_id, exc_info=True)
        finally:
            db.close()

    def retry_job(self, db, *, job_id: int, project_id: int) -> Optional[ReportJob]:
        """Re-queue a FAILED report job so the worker runs it again.

        Returns None if the job isn't in this project (endpoint → 404). Raises
        ValueError if it isn't in a retryable ('failed') state (endpoint → 409).
        Clears the prior error + lifecycle stamps so the row reads as a fresh
        attempt; retry_count is left intact as the running tally of prior
        (auto-reap + manual) retries.
        """
        # Locked read-check-write (job_transitions.retry) — the check and
        # the requeue happen under one row lock.
        try:
            job = _transitions.retry(
                db, job_id,
                allowed_from=("failed",),
                extra_conds=(ReportJob.project_id == project_id,),
                message="Re-queued by operator",
                dismissed_at=None,
            )
        except JobNotTransitionable as exc:
            raise ValueError(
                f"Only a failed job can be retried (this one is '{exc.status}')."
            ) from exc
        if job is None:
            return None
        db.commit()
        db.refresh(job)
        self.enqueue_job(job.id)
        return job

    def cancel_job(self, db, *, job_id: int, project_id: int) -> Optional[ReportJob]:
        """Cancel a QUEUED report job before the worker claims it.

        Only 'queued' is cancellable: a 'processing' job is already running on
        the worker (there's no cooperative-cancel hook), and terminal states are
        done. ``poll_and_run_one`` claims ``status = 'queued'`` only, so a
        'cancelled' row is simply never picked up. Returns None if not found in
        the project (→404); raises ValueError if not queued (→409).
        """
        # Locked read-check-write (job_transitions.cancel): without the lock
        # a worker's FOR UPDATE SKIP LOCKED claim can land between the status
        # check and the write, and the cancel would overwrite a job that is
        # already rendering.
        try:
            job = _transitions.cancel(
                db, job_id,
                allowed_from=("queued",),
                to_status="cancelled",
                extra_conds=(ReportJob.project_id == project_id,),
                message="Cancelled by operator",
            )
        except JobNotTransitionable as exc:
            raise ValueError(
                f"Only a queued job can be cancelled (this one is '{exc.status}')."
            ) from exc
        if job is None:
            return None
        db.commit()
        db.refresh(job)
        return job

    # --- worker side ------------------------------------------------------

    def poll_and_run_one(self) -> bool:
        """Claim the oldest queued job (``FOR UPDATE SKIP LOCKED``), flip it to
        processing in the locked txn, then generate it.  Returns True if a job
        was processed, False if the queue was empty."""
        db = _session_module.SessionLocal()
        try:
            # started_at doubles as this claim's fencing token: it's rewritten
            # on every claim, and the reaper nulls it on requeue. The renewal
            # thread and the completion/failure writes all condition on it, so a
            # worker whose lease was reaped and re-claimed by a peer can neither
            # keep the heartbeat warm nor publish a result over the new owner.
            claimed = _transitions.claim_oldest_queued(db, message="Generating report")
            if claimed is None:
                return False
            job_id, claimed_at = claimed
            db.commit()
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

        self._run_job(job_id, claimed_at)
        return True

    def update_heartbeat(self, db, job_id: int, claimed_at: Optional[datetime] = None) -> None:
        """Renew the lease.  Pass the claim token (``claimed_at``) wherever it
        is known — an unfenced heartbeat cannot tell two attempts apart."""
        try:
            _transitions.heartbeat(db, job_id, claimed_at)
            db.commit()
        except Exception:
            db.rollback()

    def _renew_lease_until(self, job_id: int, claimed_at: datetime, stop: threading.Event) -> None:
        """Keep ``last_heartbeat`` fresh while a render runs so the reaper does
        not treat a legitimately long job as stalled and requeue it.

        Runs on its own connection in a daemon thread (a render is one blocking
        call, so there is no in-render checkpoint to piggyback on). Fenced on
        ``started_at``: once a peer has re-claimed the job the update touches
        zero rows and this thread stops — it no longer owns the lease. This is
        the ONE heartbeat a thread may drive: unlike the worker-liveness file
        (deliberately main-loop-only, to expose a wedged loop), a warm job lease
        means exactly what a running render should mean — the job is in hand."""
        interval = max(15.0, settings.REPORT_JOB_TIMEOUT_SECONDS / 3.0)
        while not stop.wait(interval):
            db = _session_module.SessionLocal()
            try:
                written = _transitions.heartbeat(db, job_id, claimed_at)
                db.commit()
                if written == 0:
                    return  # lease lost (reaped + reclaimed) — stop renewing
            except Exception:
                db.rollback()
            finally:
                db.close()

    def _run_job(self, job_id: int, claimed_at: datetime) -> None:
        # Lazy import — ReportGenerator pulls in the whole report/insight stack.
        from app.services.report_generator import ReportGenerator

        stop = threading.Event()
        renewer = threading.Thread(
            target=self._renew_lease_until,
            args=(job_id, claimed_at, stop),
            name=f"report-lease-{job_id}",
            daemon=True,
        )
        renewer.start()

        db = _session_module.SessionLocal()
        try:
            job = db.get(ReportJob, job_id)
            if not job:
                logger.error("Report job %s not found", job_id)
                return
            try:
                # Run as the requesting user so "assigned to me" / follow filters
                # resolve the same way they did in the dialog (None if the user
                # was deleted between enqueue and run — degraded, rare).
                user = db.get(User, job.requested_by_id) if job.requested_by_id else None
                gen = ReportGenerator(db, user, project_id=job.project_id)
                filters = job.filters or {}
                report_type = job.report_type or "comprehensive"
                # These formats build the whole document in memory, so they are
                # bounded by the in-memory cap rather than the streaming one.
                # It defaults to REPORT_MAX_HOSTS (the worker isn't memory-
                # constrained the way the API thread was), but is a real lever
                # again: lower REPORT_MAX_INMEMORY_HOSTS if this worker OOMs
                # against REPORT_WORKER_MEM_LIMIT.  The lease-renewal thread keeps
                # the reaper off this row for the duration.
                hosts = gen.get_hosts_for_report(
                    filters, cap=gen.MAX_INMEMORY_REPORT_HOSTS
                )
                data, media_type, ext = self._render(gen, job.format, hosts, filters, report_type)

                ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
                filename = f"hosts_{report_type}_{ts}.{ext}"
                job_dir = self._storage_root / uuid.uuid4().hex
                job_dir.mkdir(parents=True, exist_ok=True)
                os.chmod(job_dir, 0o700)
                artifact = job_dir / filename
                artifact.write_bytes(data)

                now = datetime.now(timezone.utc)
                # Fenced completion: publish ONLY if we still own the lease. If
                # the reaper requeued this job and a peer re-claimed it (new
                # started_at), this UPDATE matches zero rows — we must not clobber
                # the peer's row nor leave two "completed" writers racing. In that
                # case our artifact is orphaned, so discard it.
                written = _transitions.complete(
                    db, job_id, claimed_at,
                    completed_at=now,
                    result_path=str(artifact),
                    result_filename=filename,
                    media_type=media_type,
                    file_size=len(data),
                    truncated=bool(gen.report_truncated),
                    message=f"Generated {filename}" + (" (truncated)" if gen.report_truncated else ""),
                    expires_at=now + timedelta(hours=settings.REPORT_ARTIFACT_TTL_HOURS),
                    last_error=None,
                )
                db.commit()
                if written == 0:
                    logger.warning(
                        "Report job %s lease lost mid-render (reaped/reclaimed) — "
                        "discarding this worker's artifact %s", job_id, job_dir,
                    )
                    shutil.rmtree(job_dir, ignore_errors=True)
                    return
                logger.info(
                    "Report job %s completed: %s (%d bytes, truncated=%s)",
                    job_id, filename, len(data), bool(gen.report_truncated),
                )
                self._notify_finished(db, job_id)
            except Exception as exc:
                logger.exception("Report job %s failed", job_id)
                db.rollback()
                msg = str(exc)[:1000]
                # Fence the failure write too — do not stamp 'failed' onto a row
                # a peer now owns after a requeue.
                written = _transitions.fail(
                    db, job_id, claimed_at, error_message=msg, last_error=msg,
                )
                db.commit()
                if written == 0:
                    logger.warning(
                        "Report job %s: stale attempt (claimed %s) — failure write "
                        "skipped; a peer owns the row", job_id, claimed_at,
                    )
                else:
                    self._notify_finished(db, job_id)
        finally:
            stop.set()
            renewer.join(timeout=5)
            db.close()

    def _notify_finished(self, db, job_id: int) -> None:
        """Notify the requester after a fenced terminal write LANDED (the
        caller checks rowcount — a stale attempt never notifies).  Runs in the
        worker's session after the job commit; best-effort, never raises."""
        try:
            from app.services.notification_service import NotificationService

            job = db.get(ReportJob, job_id)
            if job is None:
                return
            if NotificationService(db).notify_report_job_finished(job) is not None:
                db.commit()
        except Exception:  # noqa: BLE001 — a notification must never fail the job
            logger.warning("Report job %s: completion notification failed", job_id, exc_info=True)
            db.rollback()

    def _render(
        self, gen, fmt: str, hosts, filters: Dict[str, Any], report_type: str,
    ) -> Tuple[bytes, str, str]:
        """Generate one format → (bytes, media_type, file extension)."""
        if fmt == "json":
            payload = gen.generate_json_report(hosts, report_type)
            return json.dumps(payload, indent=2).encode("utf-8"), "application/json", "json"

        if fmt == "agent-package":
            return gen.generate_agent_package(hosts, filters), "application/zip", "zip"

        if fmt == "markdown-bundle":
            return gen.generate_markdown_bundle(hosts, filters), "application/zip", "zip"

        raise ValueError(f"Unsupported async report format: {fmt!r}")

    def reap_orphaned_jobs(self) -> int:
        """Re-queue (then fail) report jobs stuck in 'processing' past the
        timeout — same dead-letter mechanic as ingestion."""
        cutoff = datetime.now(timezone.utc) - timedelta(seconds=settings.REPORT_JOB_TIMEOUT_SECONDS)
        db = _session_module.SessionLocal()
        reaped = 0
        try:
            def _decide(job):
                # ``job`` is locked and retry_count already incremented.
                if job.retry_count <= _REAP_MAX_RETRIES:
                    return "requeue", {
                        "message": f"Re-queued after stall (attempt {job.retry_count}/{_REAP_MAX_RETRIES})",
                    }
                err = "Report generation stalled and exceeded its retry budget"
                return "fail", {"error_message": err, "last_error": err}

            # Each candidate is re-locked (FOR UPDATE SKIP LOCKED) with the
            # stale predicate re-applied, so a render that heartbeated in the
            # meantime keeps its job — see job_transitions.requeue_or_fail_stale.
            result = _transitions.requeue_or_fail_stale(
                db, cutoff=cutoff, max_retries=_REAP_MAX_RETRIES, decide=_decide,
            )
            reaped = result.total
            db.commit()
        except Exception:
            db.rollback()
            logger.exception("Report reaper failed")
        finally:
            db.close()
        return reaped

    def cleanup_expired(self) -> int:
        """Delete artifacts (and their job rows) past ``expires_at``."""
        now = datetime.now(timezone.utc)
        db = _session_module.SessionLocal()
        removed = 0
        try:
            expired = (
                db.query(ReportJob)
                .filter(ReportJob.expires_at.isnot(None), ReportJob.expires_at < now)
                .all()
            )
            for job in expired:
                self._remove_artifact(job)
                db.delete(job)
                removed += 1
            db.commit()
        except Exception:
            db.rollback()
            logger.exception("Report cleanup failed")
        finally:
            db.close()
        return removed

    def _remove_artifact(self, job: ReportJob) -> None:
        if not job.result_path:
            return
        try:
            job_dir = Path(job.result_path).parent
            if job_dir.exists() and job_dir.is_relative_to(self._storage_root):
                shutil.rmtree(job_dir, ignore_errors=True)
        except Exception:
            logger.debug("cleanup: could not remove artifact dir for job %s", job.id, exc_info=True)
