"""Async report generation — queue service for the report worker.

The heavy export formats (PDF, JSON, markdown-bundle, agent-package) build the
whole document in memory, so they run on a dedicated background worker instead of
the API request thread.  This service is the report-side twin of
``IngestionService``: it owns the ``report_jobs`` queue and reuses the exact same
claim mechanics — ``create_job`` → ``enqueue_job`` (pg_notify) → ``poll_and_run_one``
(``SELECT … FOR UPDATE SKIP LOCKED``) → ``_run_job`` → ``reap_orphaned_jobs`` —
plus a ``cleanup_expired`` pass that deletes artifacts past their TTL.

The generated bytes are written to a shared, worker-writable artifact dir
(``REPORT_STORAGE_DIR``, a sibling of the ingestion queue under uploads) so the
backend's download endpoint can stream the file the worker produced.
"""
from __future__ import annotations

import json
import logging
import os
import shutil
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

from sqlalchemy import text

from app.core.config import settings
# Imported as a module (not ``from … import SessionLocal``) so tests can rebind
# app.db.session.SessionLocal onto the test engine — mirrors IngestionService.
from app.db import session as _session_module
from app.db.models import ReportJob
from app.db.models_auth import User

logger = logging.getLogger(__name__)

# The formats that run async on the report worker (CSV + HTML stream synchronously
# on the API and are NOT enqueued here).
ASYNC_REPORT_FORMATS = ("pdf", "json", "agent-package", "markdown-bundle")

_REAP_MAX_RETRIES = 2


class ReportJobService:
    def __init__(self) -> None:
        self._storage_root = Path(settings.REPORT_STORAGE_DIR)

    # --- enqueue side (called from the API request thread) ----------------

    def create_job(
        self, db, *, project_id: int, requested_by_id: Optional[int],
        format: str, report_type: str, filters: Dict[str, Any],
    ) -> ReportJob:
        """Insert a queued report job and return it (the API then calls
        ``enqueue_job`` to wake the worker)."""
        job = ReportJob(
            project_id=project_id,
            requested_by_id=requested_by_id,
            format=format,
            report_type=report_type or "comprehensive",
            filters=filters or {},
            status="queued",
            message="Queued for generation",
        )
        db.add(job)
        db.commit()
        db.refresh(job)
        return job

    def enqueue_job(self, job_id: int) -> None:
        """Best-effort pg_notify so the worker wakes immediately instead of
        waiting for its next poll.  The worker claims queued rows independently
        of this hint, so a failed notify just delays pickup by one poll."""
        db = _session_module.SessionLocal()
        try:
            db.execute(text("SELECT pg_notify('report_jobs', :jid)"), {"jid": str(job_id)})
            db.commit()
        except Exception:
            db.rollback()
            logger.debug("pg_notify for report job %s failed", job_id, exc_info=True)
        finally:
            db.close()

    # --- worker side ------------------------------------------------------

    def poll_and_run_one(self) -> bool:
        """Claim the oldest queued job (``FOR UPDATE SKIP LOCKED``), flip it to
        processing in the locked txn, then generate it.  Returns True if a job
        was processed, False if the queue was empty."""
        db = _session_module.SessionLocal()
        try:
            row = db.execute(
                text(
                    "SELECT id FROM report_jobs "
                    "WHERE status = 'queued' "
                    "ORDER BY created_at LIMIT 1 "
                    "FOR UPDATE SKIP LOCKED"
                )
            ).fetchone()
            if row is None:
                return False
            job_id = row[0]
            db.execute(
                text(
                    "UPDATE report_jobs "
                    "SET status = 'processing', started_at = :now, last_heartbeat = :now, "
                    "    message = 'Generating report' "
                    "WHERE id = :jid"
                ),
                {"now": datetime.now(timezone.utc), "jid": job_id},
            )
            db.commit()
        except Exception:
            db.rollback()
            raise
        finally:
            db.close()

        self._run_job(job_id)
        return True

    def update_heartbeat(self, db, job_id: int) -> None:
        try:
            db.execute(
                text("UPDATE report_jobs SET last_heartbeat = :hb WHERE id = :jid"),
                {"hb": datetime.now(timezone.utc), "jid": job_id},
            )
            db.commit()
        except Exception:
            db.rollback()

    def _run_job(self, job_id: int) -> None:
        # Lazy import — ReportGenerator pulls in the whole report/insight stack.
        from app.api.v1.endpoints.reports import ReportGenerator

        db = _session_module.SessionLocal()
        try:
            job = db.get(ReportJob, job_id)
            if not job:
                logger.error("Report job %s not found", job_id)
                return
            try:
                # Run as the requesting user so "assigned to me" / follow filters
                # resolve the same way they did in the dialog (None if the user
                # was deleted between enqueue and run — degraded, rare).
                user = db.get(User, job.requested_by_id) if job.requested_by_id else None
                gen = ReportGenerator(db, user, project_id=job.project_id)
                filters = job.filters or {}
                report_type = job.report_type or "comprehensive"
                # On the worker we're not memory-constrained like the API, so the
                # async formats get the full 50k cap back.
                hosts = gen.get_hosts_for_report(filters, cap=gen.MAX_REPORT_HOSTS)
                data, media_type, ext = self._render(gen, job.format, hosts, filters, report_type)
                self.update_heartbeat(db, job_id)  # a long render leaves the row stale

                ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
                filename = f"hosts_{report_type}_{ts}.{ext}"
                job_dir = self._storage_root / uuid.uuid4().hex
                job_dir.mkdir(parents=True, exist_ok=True)
                os.chmod(job_dir, 0o700)
                artifact = job_dir / filename
                artifact.write_bytes(data)

                now = datetime.now(timezone.utc)
                job = db.get(ReportJob, job_id)
                job.status = "completed"
                job.completed_at = now
                job.result_path = str(artifact)
                job.result_filename = filename
                job.media_type = media_type
                job.file_size = len(data)
                job.truncated = bool(gen.report_truncated)
                job.message = f"Generated {filename}" + (" (truncated)" if gen.report_truncated else "")
                job.expires_at = now + timedelta(hours=settings.REPORT_ARTIFACT_TTL_HOURS)
                job.last_error = None
                db.commit()
                logger.info(
                    "Report job %s completed: %s (%d bytes, truncated=%s)",
                    job_id, filename, len(data), job.truncated,
                )
            except Exception as exc:
                logger.exception("Report job %s failed", job_id)
                db.rollback()
                job = db.get(ReportJob, job_id)
                if job:
                    msg = str(exc)[:1000]
                    job.status = "failed"
                    job.error_message = msg
                    job.last_error = msg
                    job.completed_at = datetime.now(timezone.utc)
                    db.commit()
        finally:
            db.close()

    def _render(
        self, gen, fmt: str, hosts, filters: Dict[str, Any], report_type: str,
    ) -> Tuple[bytes, str, str]:
        """Generate one format → (bytes, media_type, file extension)."""
        if fmt == "pdf":
            html = gen.generate_html_report(hosts, filters, report_type, for_pdf=True)
            try:
                # OSError (not just ImportError) when the native Pango/Cairo libs
                # are missing — weasyprint dlopen's them at import time.
                from weasyprint import HTML
            except (ImportError, OSError) as exc:
                raise RuntimeError(
                    "PDF export unavailable: the server's PDF rendering libraries are not installed."
                ) from exc

            def _deny_all_fetcher(url, *args, **kwargs):
                # Untrusted scan data flows into this HTML — WeasyPrint must never
                # fetch a remote URL or read a local file. The template is
                # self-contained (inline CSS), so this should never fire.
                raise ValueError(f"External resource blocked in PDF report: {url}")

            return HTML(string=html, url_fetcher=_deny_all_fetcher).write_pdf(), "application/pdf", "pdf"

        if fmt == "json":
            payload = gen.generate_json_report(hosts, report_type)
            return json.dumps(payload, indent=2).encode("utf-8"), "application/json", "json"

        if fmt == "agent-package":
            return gen.generate_agent_package(hosts, filters), "application/zip", "zip"

        if fmt == "markdown-bundle":
            return gen.generate_markdown_bundle(hosts, filters), "application/zip", "zip"

        raise ValueError(f"Unsupported async report format: {fmt!r}")

    def reap_orphaned_jobs(self) -> int:
        """Re-queue (then fail) report jobs stuck in 'processing' past the
        timeout — same dead-letter mechanic as ingestion."""
        cutoff = datetime.now(timezone.utc) - timedelta(seconds=settings.REPORT_JOB_TIMEOUT_SECONDS)
        db = _session_module.SessionLocal()
        reaped = 0
        try:
            stuck = (
                db.query(ReportJob)
                .filter(
                    ReportJob.status == "processing",
                    (
                        (ReportJob.last_heartbeat.is_(None) & (ReportJob.started_at < cutoff))
                        | (ReportJob.last_heartbeat < cutoff)
                    ),
                )
                .all()
            )
            for job in stuck:
                job.retry_count = (job.retry_count or 0) + 1
                if job.retry_count <= _REAP_MAX_RETRIES:
                    job.status = "queued"
                    job.started_at = None
                    job.last_heartbeat = None
                    job.message = f"Re-queued after stall (attempt {job.retry_count}/{_REAP_MAX_RETRIES})"
                else:
                    job.status = "failed"
                    job.error_message = "Report generation stalled and exceeded its retry budget"
                    job.last_error = job.error_message
                    job.completed_at = datetime.now(timezone.utc)
                reaped += 1
            db.commit()
        except Exception:
            db.rollback()
            logger.exception("Report reaper failed")
        finally:
            db.close()
        return reaped

    def cleanup_expired(self) -> int:
        """Delete artifacts (and their job rows) past ``expires_at``."""
        now = datetime.now(timezone.utc)
        db = _session_module.SessionLocal()
        removed = 0
        try:
            expired = (
                db.query(ReportJob)
                .filter(ReportJob.expires_at.isnot(None), ReportJob.expires_at < now)
                .all()
            )
            for job in expired:
                self._remove_artifact(job)
                db.delete(job)
                removed += 1
            db.commit()
        except Exception:
            db.rollback()
            logger.exception("Report cleanup failed")
        finally:
            db.close()
        return removed

    def _remove_artifact(self, job: ReportJob) -> None:
        if not job.result_path:
            return
        try:
            job_dir = Path(job.result_path).parent
            if job_dir.exists() and job_dir.is_relative_to(self._storage_root):
                shutil.rmtree(job_dir, ignore_errors=True)
        except Exception:
            logger.debug("cleanup: could not remove artifact dir for job %s", job.id, exc_info=True)
