"""baseline schema

Revision ID: b46cd59c17f5
Revises: 
Create Date: 2026-05-15 02:38:36.367956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46cd59c17f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vulnerability_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('cvss_v3_score', sa.Float(), nullable=True),
    sa.Column('cvss_v3_vector', sa.String(length=200), nullable=True),
    sa.Column('cvss_v2_score', sa.Float(), nullable=True),
    sa.Column('cvss_v2_vector', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('attack_vector', sa.String(length=50), nullable=True),
    sa.Column('attack_complexity', sa.String(length=20), nullable=True),
    sa.Column('exploitability_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_database_cve_id'), 'vulnerability_database', ['cve_id'], unique=True)
    op.create_index(op.f('ix_vulnerability_database_id'), 'vulnerability_database', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('llm_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('extra_config', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_llm_provider_user_name')
    )
    op.create_index(op.f('ix_llm_providers_id'), 'llm_providers', ['id'], unique=False)
    op.create_index(op.f('ix_llm_providers_user_id'), 'llm_providers', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('security_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=True),
    sa.Column('password_require_uppercase', sa.Boolean(), nullable=True),
    sa.Column('password_require_lowercase', sa.Boolean(), nullable=True),
    sa.Column('password_require_numbers', sa.Boolean(), nullable=True),
    sa.Column('password_require_symbols', sa.Boolean(), nullable=True),
    sa.Column('password_expiry_days', sa.Integer(), nullable=True),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=True),
    sa.Column('max_failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('audit_retention_days', sa.Integer(), nullable=True),
    sa.Column('require_audit_login', sa.Boolean(), nullable=True),
    sa.Column('require_audit_data_access', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_policies_id'), 'security_policies', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_jti'), 'user_sessions', ['token_jti'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'owner_id', name='uq_agent_per_user_project')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_agents_project_id'), 'agents', ['project_id'], unique=False)
    op.create_table('dns_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_records_domain'), 'dns_records', ['domain'], unique=False)
    op.create_index(op.f('ix_dns_records_id'), 'dns_records', ['id'], unique=False)
    op.create_index(op.f('ix_dns_records_project_id'), 'dns_records', ['project_id'], unique=False)
    op.create_table('host_filter_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filter_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'name', name='uq_host_filter_view_name')
    )
    op.create_index(op.f('ix_host_filter_views_id'), 'host_filter_views', ['id'], unique=False)
    op.create_index(op.f('ix_host_filter_views_project_id'), 'host_filter_views', ['project_id'], unique=False)
    op.create_index(op.f('ix_host_filter_views_user_id'), 'host_filter_views', ['user_id'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('integration_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('secret2_encrypted', sa.Text(), nullable=True),
    sa.Column('extra_config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'name', name='uq_integration_user_project_name')
    )
    op.create_index(op.f('ix_integration_credentials_id'), 'integration_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_integration_credentials_project_id'), 'integration_credentials', ['project_id'], unique=False)
    op.create_index(op.f('ix_integration_credentials_user_id'), 'integration_credentials', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('parse_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('file_preview', sa.Text(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_errors_id'), 'parse_errors', ['id'], unique=False)
    op.create_index(op.f('ix_parse_errors_project_id'), 'parse_errors', ['project_id'], unique=False)
    op.create_table('project_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    op.create_index(op.f('ix_project_memberships_id'), 'project_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_project_memberships_project_id'), 'project_memberships', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_memberships_user_id'), 'project_memberships', ['user_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('xml_output_version', sa.String(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_table('scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scopes_id'), 'scopes', ['id'], unique=False)
    op.create_index(op.f('ix_scopes_project_id'), 'scopes', ['project_id'], unique=False)
    op.create_table('conflict_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('previous_confidence', sa.Integer(), nullable=True),
    sa.Column('previous_scan_id', sa.Integer(), nullable=True),
    sa.Column('previous_method', sa.String(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('new_confidence', sa.Integer(), nullable=True),
    sa.Column('new_scan_id', sa.Integer(), nullable=True),
    sa.Column('new_method', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['new_scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['previous_scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_history_id'), 'conflict_history', ['id'], unique=False)
    op.create_table('data_source_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('tool_version', sa.String(), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('total_hosts_scanned', sa.Integer(), nullable=True),
    sa.Column('successful_responses', sa.Integer(), nullable=True),
    sa.Column('failed_responses', sa.Integer(), nullable=True),
    sa.Column('timeout_count', sa.Integer(), nullable=True),
    sa.Column('scan_duration_seconds', sa.Float(), nullable=True),
    sa.Column('scan_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('overall_quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_metadata_id'), 'data_source_metadata', ['id'], unique=False)
    op.create_table('hosts_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('state_reason', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('os_family', sa.String(), nullable=True),
    sa.Column('os_generation', sa.String(), nullable=True),
    sa.Column('os_type', sa.String(), nullable=True),
    sa.Column('os_vendor', sa.String(), nullable=True),
    sa.Column('os_accuracy', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated_scan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_updated_scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ip_address', name='uq_project_ip')
    )
    op.create_index('idx_host_ip_address', 'hosts_v2', ['ip_address'], unique=False)
    op.create_index(op.f('ix_hosts_v2_id'), 'hosts_v2', ['id'], unique=False)
    op.create_index(op.f('ix_hosts_v2_ip_address'), 'hosts_v2', ['ip_address'], unique=False)
    op.create_index(op.f('ix_hosts_v2_project_id'), 'hosts_v2', ['project_id'], unique=False)
    op.create_table('out_of_scope_hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ports', sa.JSON(), nullable=True),
    sa.Column('tool_source', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_out_of_scope_hosts_id'), 'out_of_scope_hosts', ['id'], unique=False)
    op.create_index(op.f('ix_out_of_scope_hosts_ip_address'), 'out_of_scope_hosts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_out_of_scope_hosts_project_id'), 'out_of_scope_hosts', ['project_id'], unique=False)
    op.create_table('recon_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('started_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploads_submitted', sa.Integer(), nullable=False),
    sa.Column('scans_ingested', sa.Integer(), nullable=False),
    sa.Column('hosts_discovered', sa.Integer(), nullable=False),
    sa.Column('ports_discovered', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recon_session_project', 'recon_sessions', ['project_id'], unique=False)
    op.create_index('idx_recon_session_scope', 'recon_sessions', ['scope_id'], unique=False)
    op.create_index('idx_recon_session_status', 'recon_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_recon_sessions_id'), 'recon_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_recon_sessions_project_id'), 'recon_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_recon_sessions_scope_id'), 'recon_sessions', ['scope_id'], unique=False)
    op.create_table('scan_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('numservices', sa.Integer(), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_info_id'), 'scan_info', ['id'], unique=False)
    op.create_table('subnets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnets_cidr'), 'subnets', ['cidr'], unique=False)
    op.create_index(op.f('ix_subnets_id'), 'subnets', ['id'], unique=False)
    op.create_table('test_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('filter_criteria', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_test_plan_project_version')
    )
    op.create_index('idx_test_plan_project_status', 'test_plans', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_test_plans_agent_id'), 'test_plans', ['agent_id'], unique=False)
    op.create_index(op.f('ix_test_plans_created_by_user_id'), 'test_plans', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_test_plans_id'), 'test_plans', ['id'], unique=False)
    op.create_index(op.f('ix_test_plans_project_id'), 'test_plans', ['project_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('test_plan_id', sa.Integer(), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('allowed_ips', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_scope_id'), 'api_keys', ['scope_id'], unique=False)
    op.create_index(op.f('ix_api_keys_test_plan_id'), 'api_keys', ['test_plan_id'], unique=False)
    op.create_table('execution_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_plan_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('started_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('bundle_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exec_session_plan', 'execution_sessions', ['test_plan_id'], unique=False)
    op.create_index(op.f('ix_execution_sessions_bundle_id'), 'execution_sessions', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_execution_sessions_id'), 'execution_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_execution_sessions_test_plan_id'), 'execution_sessions', ['test_plan_id'], unique=False)
    op.create_table('host_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('attribute_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_attributes_attribute_type'), 'host_attributes', ['attribute_type'], unique=False)
    op.create_index(op.f('ix_host_attributes_host_id'), 'host_attributes', ['host_id'], unique=False)
    op.create_index(op.f('ix_host_attributes_id'), 'host_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_host_attributes_scan_id'), 'host_attributes', ['scan_id'], unique=False)
    op.create_index(op.f('ix_host_attributes_source'), 'host_attributes', ['source'], unique=False)
    op.create_table('host_confidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('additional_factors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_confidence_id'), 'host_confidence', ['id'], unique=False)
    op.create_table('host_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WATCHING', 'IN_REVIEW', 'REVIEWED', name='followstatus'), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'user_id', name='uq_host_follow_user')
    )
    op.create_index(op.f('ix_host_follows_id'), 'host_follows', ['id'], unique=False)
    op.create_table('host_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='notestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['host_notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_notes_id'), 'host_notes', ['id'], unique=False)
    op.create_table('host_risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('vulnerability_count', sa.Integer(), nullable=True),
    sa.Column('critical_vulnerabilities', sa.Integer(), nullable=True),
    sa.Column('high_vulnerabilities', sa.Integer(), nullable=True),
    sa.Column('medium_vulnerabilities', sa.Integer(), nullable=True),
    sa.Column('low_vulnerabilities', sa.Integer(), nullable=True),
    sa.Column('exposed_services', sa.Integer(), nullable=True),
    sa.Column('dangerous_ports', sa.Integer(), nullable=True),
    sa.Column('attack_surface_score', sa.Float(), nullable=True),
    sa.Column('patch_urgency_score', sa.Float(), nullable=True),
    sa.Column('exposure_risk_score', sa.Float(), nullable=True),
    sa.Column('configuration_risk_score', sa.Float(), nullable=True),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_risk_assessments_host_id'), 'host_risk_assessments', ['host_id'], unique=False)
    op.create_index(op.f('ix_host_risk_assessments_id'), 'host_risk_assessments', ['id'], unique=False)
    op.create_table('host_scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('state_at_scan', sa.String(), nullable=True),
    sa.Column('hostname_at_scan', sa.String(), nullable=True),
    sa.Column('os_info_updated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'scan_id', name='uq_host_scan')
    )
    op.create_index('idx_host_scan_discovered', 'host_scan_history', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_host_scan_history_id'), 'host_scan_history', ['id'], unique=False)
    op.create_table('host_scripts_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'script_id', name='uq_host_script')
    )
    op.create_index('idx_host_script_id', 'host_scripts_v2', ['script_id'], unique=False)
    op.create_index(op.f('ix_host_scripts_v2_id'), 'host_scripts_v2', ['id'], unique=False)
    op.create_table('host_subnet_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('subnet_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'subnet_id', name='uq_host_subnet')
    )
    op.create_index(op.f('ix_host_subnet_mappings_host_id'), 'host_subnet_mappings', ['host_id'], unique=False)
    op.create_index(op.f('ix_host_subnet_mappings_id'), 'host_subnet_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_host_subnet_mappings_subnet_id'), 'host_subnet_mappings', ['subnet_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('parse_error_id', sa.Integer(), nullable=True),
    sa.Column('recon_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parse_error_id'], ['parse_errors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['recon_session_id'], ['recon_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_project_id'), 'ingestion_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_recon_session_id'), 'ingestion_jobs', ['recon_session_id'], unique=False)
    op.create_table('netexec_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('auth_success', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('shares', sa.JSON(), nullable=True),
    sa.Column('users', sa.JSON(), nullable=True),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('policies', sa.JSON(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('domain_name', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('arch', sa.String(), nullable=True),
    sa.Column('service_banner', sa.Text(), nullable=True),
    sa.Column('service_version', sa.String(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('connection_stable', sa.Boolean(), nullable=True),
    sa.Column('multiple_confirmations', sa.Boolean(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netexec_results_id'), 'netexec_results', ['id'], unique=False)
    op.create_table('ports_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('service_product', sa.String(), nullable=True),
    sa.Column('service_version', sa.String(), nullable=True),
    sa.Column('service_extrainfo', sa.Text(), nullable=True),
    sa.Column('service_method', sa.String(), nullable=True),
    sa.Column('service_conf', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated_scan_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['last_updated_scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'port_number', 'protocol', name='uq_host_port_protocol')
    )
    op.create_index('idx_port_number_protocol', 'ports_v2', ['port_number', 'protocol'], unique=False)
    op.create_index('idx_port_state', 'ports_v2', ['state'], unique=False)
    op.create_index(op.f('ix_ports_v2_id'), 'ports_v2', ['id'], unique=False)
    op.create_index(op.f('ix_ports_v2_port_number'), 'ports_v2', ['port_number'], unique=False)
    op.create_table('test_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_plan_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('test_phase', sa.String(length=30), nullable=False),
    sa.Column('proposed_tests', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('results_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_plan_id', 'host_id', name='uq_plan_host')
    )
    op.create_index('idx_entry_plan_status', 'test_plan_entries', ['test_plan_id', 'status'], unique=False)
    op.create_index(op.f('ix_test_plan_entries_host_id'), 'test_plan_entries', ['host_id'], unique=False)
    op.create_index(op.f('ix_test_plan_entries_id'), 'test_plan_entries', ['id'], unique=False)
    op.create_index(op.f('ix_test_plan_entries_test_plan_id'), 'test_plan_entries', ['test_plan_id'], unique=False)
    op.create_table('agent_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('test_plan_id', sa.Integer(), nullable=True),
    sa.Column('execution_session_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('api_critiques', sa.JSON(), nullable=True),
    sa.Column('tool_suggestions', sa.JSON(), nullable=True),
    sa.Column('friction_notes', sa.Text(), nullable=True),
    sa.Column('agent_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_session_id'], ['execution_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_feedback_created_desc', 'agent_feedback', ['created_at'], unique=False)
    op.create_index('idx_agent_feedback_source', 'agent_feedback', ['source'], unique=False)
    op.create_index('idx_agent_feedback_status', 'agent_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_agent_feedback_id'), 'agent_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_project_id'), 'agent_feedback', ['project_id'], unique=False)
    op.create_table('host_sanity_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_session_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('target_ip', sa.String(length=45), nullable=False),
    sa.Column('port_checked', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('dns_result', sa.String(length=255), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['test_plan_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_session_id'], ['execution_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_session_id', 'entry_id', 'method', name='uq_sanity_check_session_entry_method')
    )
    op.create_index('idx_sanity_check_session', 'host_sanity_checks', ['execution_session_id'], unique=False)
    op.create_index(op.f('ix_host_sanity_checks_execution_session_id'), 'host_sanity_checks', ['execution_session_id'], unique=False)
    op.create_index(op.f('ix_host_sanity_checks_id'), 'host_sanity_checks', ['id'], unique=False)
    op.create_table('host_vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('exploitability', sa.String(length=50), nullable=True),
    sa.Column('affected_software', sa.String(length=200), nullable=True),
    sa.Column('affected_version', sa.String(length=100), nullable=True),
    sa.Column('port_number', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('patch_available', sa.Boolean(), nullable=True),
    sa.Column('patch_url', sa.String(length=500), nullable=True),
    sa.Column('patch_priority', sa.String(length=20), nullable=True),
    sa.Column('discovery_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['host_risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_vulnerabilities_cve_id'), 'host_vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_host_vulnerabilities_host_id'), 'host_vulnerabilities', ['host_id'], unique=False)
    op.create_index(op.f('ix_host_vulnerabilities_id'), 'host_vulnerabilities', ['id'], unique=False)
    op.create_table('imported_result_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_session_id', sa.Integer(), nullable=False),
    sa.Column('test_plan_id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('sanity_checks_count', sa.Integer(), nullable=False),
    sa.Column('feedback_extracted', sa.Boolean(), nullable=False),
    sa.Column('parse_errors', sa.JSON(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['execution_session_id'], ['execution_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_result_files_bundle_id'), 'imported_result_files', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_imported_result_files_execution_session_id'), 'imported_result_files', ['execution_session_id'], unique=False)
    op.create_index(op.f('ix_imported_result_files_id'), 'imported_result_files', ['id'], unique=False)
    op.create_table('note_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['host_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'user_id', name='uq_note_mention_user')
    )
    op.create_index(op.f('ix_note_mentions_id'), 'note_mentions', ['id'], unique=False)
    op.create_table('port_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('attribute_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_attributes_attribute_type'), 'port_attributes', ['attribute_type'], unique=False)
    op.create_index(op.f('ix_port_attributes_id'), 'port_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_port_attributes_port_id'), 'port_attributes', ['port_id'], unique=False)
    op.create_index(op.f('ix_port_attributes_scan_id'), 'port_attributes', ['scan_id'], unique=False)
    op.create_index(op.f('ix_port_attributes_source'), 'port_attributes', ['source'], unique=False)
    op.create_table('port_confidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('additional_factors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_confidence_id'), 'port_confidence', ['id'], unique=False)
    op.create_table('port_scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('state_at_scan', sa.String(), nullable=True),
    sa.Column('service_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id', 'scan_id', name='uq_port_scan')
    )
    op.create_index('idx_port_scan_discovered', 'port_scan_history', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_port_scan_history_id'), 'port_scan_history', ['id'], unique=False)
    op.create_table('risk_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('implementation_effort', sa.String(length=20), nullable=True),
    sa.Column('estimated_risk_reduction', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['host_risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_recommendations_id'), 'risk_recommendations', ['id'], unique=False)
    op.create_table('scripts_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['ports_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id', 'script_id', name='uq_port_script')
    )
    op.create_index('idx_script_id', 'scripts_v2', ['script_id'], unique=False)
    op.create_index(op.f('ix_scripts_v2_id'), 'scripts_v2', ['id'], unique=False)
    op.create_table('security_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('affected_component', sa.String(length=200), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('remediation_effort', sa.String(length=20), nullable=True),
    sa.Column('discovery_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['host_risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_findings_host_id'), 'security_findings', ['host_id'], unique=False)
    op.create_index(op.f('ix_security_findings_id'), 'security_findings', ['id'], unique=False)
    op.create_table('test_execution_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_session_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('test_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('command_run', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('findings_summary', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_finding', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['test_plan_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_session_id'], ['execution_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_session_id', 'entry_id', 'test_index', name='uq_exec_result_session_entry_test')
    )
    op.create_index('idx_test_result_entry', 'test_execution_results', ['entry_id'], unique=False)
    op.create_index(op.f('ix_test_execution_results_entry_id'), 'test_execution_results', ['entry_id'], unique=False)
    op.create_index(op.f('ix_test_execution_results_execution_session_id'), 'test_execution_results', ['execution_session_id'], unique=False)
    op.create_index(op.f('ix_test_execution_results_id'), 'test_execution_results', ['id'], unique=False)
    op.create_table('test_plan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_plan_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('field_changed', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['test_plan_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_plan_time', 'test_plan_history', ['test_plan_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_test_plan_history_id'), 'test_plan_history', ['id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('plugin_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', 'UNKNOWN', name='vulnerabilityseverity'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=200), nullable=True),
    sa.Column('source', sa.Enum('NESSUS', 'OPENVAS', 'NIKTO', 'NMAP', 'NETEXEC', 'SHODAN', 'CVE_API', 'MANUAL', name='vulnerabilitysource'), nullable=False),
    sa.Column('source_plugin_name', sa.String(length=200), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('exploitable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports_v2.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_host_id'), 'vulnerabilities', ['host_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_plugin_id'), 'vulnerabilities', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_port_id'), 'vulnerabilities', ['port_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_scan_id'), 'vulnerabilities', ['scan_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_source'), 'vulnerabilities', ['source'], unique=False)
    op.create_table('web_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('server_header', sa.String(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('favicon_hash', sa.String(length=64), nullable=True),
    sa.Column('tls_info', sa.JSON(), nullable=True),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.Column('page_text', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['ports_v2.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'url', 'source', name='uq_web_interface_scan_url_source')
    )
    op.create_index('idx_web_interface_favicon', 'web_interfaces', ['favicon_hash'], unique=False)
    op.create_index('idx_web_interface_host', 'web_interfaces', ['host_id'], unique=False)
    op.create_index(op.f('ix_web_interfaces_favicon_hash'), 'web_interfaces', ['favicon_hash'], unique=False)
    op.create_index(op.f('ix_web_interfaces_host_id'), 'web_interfaces', ['host_id'], unique=False)
    op.create_index(op.f('ix_web_interfaces_id'), 'web_interfaces', ['id'], unique=False)
    op.create_index(op.f('ix_web_interfaces_ip_address'), 'web_interfaces', ['ip_address'], unique=False)
    op.create_index(op.f('ix_web_interfaces_port_id'), 'web_interfaces', ['port_id'], unique=False)
    op.create_index(op.f('ix_web_interfaces_project_id'), 'web_interfaces', ['project_id'], unique=False)
    op.create_index(op.f('ix_web_interfaces_scan_id'), 'web_interfaces', ['scan_id'], unique=False)
    op.create_index(op.f('ix_web_interfaces_url'), 'web_interfaces', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_interfaces_url'), table_name='web_interfaces')
    op.drop_index(op.f('ix_web_interfaces_scan_id'), table_name='web_interfaces')
    op.drop_index(op.f('ix_web_interfaces_project_id'), table_name='web_interfaces')
    op.drop_index(op.f('ix_web_interfaces_port_id'), table_name='web_interfaces')
    op.drop_index(op.f('ix_web_interfaces_ip_address'), table_name='web_interfaces')
    op.drop_index(op.f('ix_web_interfaces_id'), table_name='web_interfaces')
    op.drop_index(op.f('ix_web_interfaces_host_id'), table_name='web_interfaces')
    op.drop_index(op.f('ix_web_interfaces_favicon_hash'), table_name='web_interfaces')
    op.drop_index('idx_web_interface_host', table_name='web_interfaces')
    op.drop_index('idx_web_interface_favicon', table_name='web_interfaces')
    op.drop_table('web_interfaces')
    op.drop_index(op.f('ix_vulnerabilities_source'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_scan_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_port_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_plugin_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_host_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_test_plan_history_id'), table_name='test_plan_history')
    op.drop_index('idx_history_plan_time', table_name='test_plan_history')
    op.drop_table('test_plan_history')
    op.drop_index(op.f('ix_test_execution_results_id'), table_name='test_execution_results')
    op.drop_index(op.f('ix_test_execution_results_execution_session_id'), table_name='test_execution_results')
    op.drop_index(op.f('ix_test_execution_results_entry_id'), table_name='test_execution_results')
    op.drop_index('idx_test_result_entry', table_name='test_execution_results')
    op.drop_table('test_execution_results')
    op.drop_index(op.f('ix_security_findings_id'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_host_id'), table_name='security_findings')
    op.drop_table('security_findings')
    op.drop_index(op.f('ix_scripts_v2_id'), table_name='scripts_v2')
    op.drop_index('idx_script_id', table_name='scripts_v2')
    op.drop_table('scripts_v2')
    op.drop_index(op.f('ix_risk_recommendations_id'), table_name='risk_recommendations')
    op.drop_table('risk_recommendations')
    op.drop_index(op.f('ix_port_scan_history_id'), table_name='port_scan_history')
    op.drop_index('idx_port_scan_discovered', table_name='port_scan_history')
    op.drop_table('port_scan_history')
    op.drop_index(op.f('ix_port_confidence_id'), table_name='port_confidence')
    op.drop_table('port_confidence')
    op.drop_index(op.f('ix_port_attributes_source'), table_name='port_attributes')
    op.drop_index(op.f('ix_port_attributes_scan_id'), table_name='port_attributes')
    op.drop_index(op.f('ix_port_attributes_port_id'), table_name='port_attributes')
    op.drop_index(op.f('ix_port_attributes_id'), table_name='port_attributes')
    op.drop_index(op.f('ix_port_attributes_attribute_type'), table_name='port_attributes')
    op.drop_table('port_attributes')
    op.drop_index(op.f('ix_note_mentions_id'), table_name='note_mentions')
    op.drop_table('note_mentions')
    op.drop_index(op.f('ix_imported_result_files_id'), table_name='imported_result_files')
    op.drop_index(op.f('ix_imported_result_files_execution_session_id'), table_name='imported_result_files')
    op.drop_index(op.f('ix_imported_result_files_bundle_id'), table_name='imported_result_files')
    op.drop_table('imported_result_files')
    op.drop_index(op.f('ix_host_vulnerabilities_id'), table_name='host_vulnerabilities')
    op.drop_index(op.f('ix_host_vulnerabilities_host_id'), table_name='host_vulnerabilities')
    op.drop_index(op.f('ix_host_vulnerabilities_cve_id'), table_name='host_vulnerabilities')
    op.drop_table('host_vulnerabilities')
    op.drop_index(op.f('ix_host_sanity_checks_id'), table_name='host_sanity_checks')
    op.drop_index(op.f('ix_host_sanity_checks_execution_session_id'), table_name='host_sanity_checks')
    op.drop_index('idx_sanity_check_session', table_name='host_sanity_checks')
    op.drop_table('host_sanity_checks')
    op.drop_index(op.f('ix_agent_feedback_project_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_id'), table_name='agent_feedback')
    op.drop_index('idx_agent_feedback_status', table_name='agent_feedback')
    op.drop_index('idx_agent_feedback_source', table_name='agent_feedback')
    op.drop_index('idx_agent_feedback_created_desc', table_name='agent_feedback')
    op.drop_table('agent_feedback')
    op.drop_index(op.f('ix_test_plan_entries_test_plan_id'), table_name='test_plan_entries')
    op.drop_index(op.f('ix_test_plan_entries_id'), table_name='test_plan_entries')
    op.drop_index(op.f('ix_test_plan_entries_host_id'), table_name='test_plan_entries')
    op.drop_index('idx_entry_plan_status', table_name='test_plan_entries')
    op.drop_table('test_plan_entries')
    op.drop_index(op.f('ix_ports_v2_port_number'), table_name='ports_v2')
    op.drop_index(op.f('ix_ports_v2_id'), table_name='ports_v2')
    op.drop_index('idx_port_state', table_name='ports_v2')
    op.drop_index('idx_port_number_protocol', table_name='ports_v2')
    op.drop_table('ports_v2')
    op.drop_index(op.f('ix_netexec_results_id'), table_name='netexec_results')
    op.drop_table('netexec_results')
    op.drop_index(op.f('ix_ingestion_jobs_recon_session_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_project_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_host_subnet_mappings_subnet_id'), table_name='host_subnet_mappings')
    op.drop_index(op.f('ix_host_subnet_mappings_id'), table_name='host_subnet_mappings')
    op.drop_index(op.f('ix_host_subnet_mappings_host_id'), table_name='host_subnet_mappings')
    op.drop_table('host_subnet_mappings')
    op.drop_index(op.f('ix_host_scripts_v2_id'), table_name='host_scripts_v2')
    op.drop_index('idx_host_script_id', table_name='host_scripts_v2')
    op.drop_table('host_scripts_v2')
    op.drop_index(op.f('ix_host_scan_history_id'), table_name='host_scan_history')
    op.drop_index('idx_host_scan_discovered', table_name='host_scan_history')
    op.drop_table('host_scan_history')
    op.drop_index(op.f('ix_host_risk_assessments_id'), table_name='host_risk_assessments')
    op.drop_index(op.f('ix_host_risk_assessments_host_id'), table_name='host_risk_assessments')
    op.drop_table('host_risk_assessments')
    op.drop_index(op.f('ix_host_notes_id'), table_name='host_notes')
    op.drop_table('host_notes')
    op.drop_index(op.f('ix_host_follows_id'), table_name='host_follows')
    op.drop_table('host_follows')
    op.drop_index(op.f('ix_host_confidence_id'), table_name='host_confidence')
    op.drop_table('host_confidence')
    op.drop_index(op.f('ix_host_attributes_source'), table_name='host_attributes')
    op.drop_index(op.f('ix_host_attributes_scan_id'), table_name='host_attributes')
    op.drop_index(op.f('ix_host_attributes_id'), table_name='host_attributes')
    op.drop_index(op.f('ix_host_attributes_host_id'), table_name='host_attributes')
    op.drop_index(op.f('ix_host_attributes_attribute_type'), table_name='host_attributes')
    op.drop_table('host_attributes')
    op.drop_index(op.f('ix_execution_sessions_test_plan_id'), table_name='execution_sessions')
    op.drop_index(op.f('ix_execution_sessions_id'), table_name='execution_sessions')
    op.drop_index(op.f('ix_execution_sessions_bundle_id'), table_name='execution_sessions')
    op.drop_index('idx_exec_session_plan', table_name='execution_sessions')
    op.drop_table('execution_sessions')
    op.drop_index(op.f('ix_api_keys_test_plan_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_scope_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_test_plans_project_id'), table_name='test_plans')
    op.drop_index(op.f('ix_test_plans_id'), table_name='test_plans')
    op.drop_index(op.f('ix_test_plans_created_by_user_id'), table_name='test_plans')
    op.drop_index(op.f('ix_test_plans_agent_id'), table_name='test_plans')
    op.drop_index('idx_test_plan_project_status', table_name='test_plans')
    op.drop_table('test_plans')
    op.drop_index(op.f('ix_subnets_id'), table_name='subnets')
    op.drop_index(op.f('ix_subnets_cidr'), table_name='subnets')
    op.drop_table('subnets')
    op.drop_index(op.f('ix_scan_info_id'), table_name='scan_info')
    op.drop_table('scan_info')
    op.drop_index(op.f('ix_recon_sessions_scope_id'), table_name='recon_sessions')
    op.drop_index(op.f('ix_recon_sessions_project_id'), table_name='recon_sessions')
    op.drop_index(op.f('ix_recon_sessions_id'), table_name='recon_sessions')
    op.drop_index('idx_recon_session_status', table_name='recon_sessions')
    op.drop_index('idx_recon_session_scope', table_name='recon_sessions')
    op.drop_index('idx_recon_session_project', table_name='recon_sessions')
    op.drop_table('recon_sessions')
    op.drop_index(op.f('ix_out_of_scope_hosts_project_id'), table_name='out_of_scope_hosts')
    op.drop_index(op.f('ix_out_of_scope_hosts_ip_address'), table_name='out_of_scope_hosts')
    op.drop_index(op.f('ix_out_of_scope_hosts_id'), table_name='out_of_scope_hosts')
    op.drop_table('out_of_scope_hosts')
    op.drop_index(op.f('ix_hosts_v2_project_id'), table_name='hosts_v2')
    op.drop_index(op.f('ix_hosts_v2_ip_address'), table_name='hosts_v2')
    op.drop_index(op.f('ix_hosts_v2_id'), table_name='hosts_v2')
    op.drop_index('idx_host_ip_address', table_name='hosts_v2')
    op.drop_table('hosts_v2')
    op.drop_index(op.f('ix_data_source_metadata_id'), table_name='data_source_metadata')
    op.drop_table('data_source_metadata')
    op.drop_index(op.f('ix_conflict_history_id'), table_name='conflict_history')
    op.drop_table('conflict_history')
    op.drop_index(op.f('ix_scopes_project_id'), table_name='scopes')
    op.drop_index(op.f('ix_scopes_id'), table_name='scopes')
    op.drop_table('scopes')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_project_memberships_user_id'), table_name='project_memberships')
    op.drop_index(op.f('ix_project_memberships_project_id'), table_name='project_memberships')
    op.drop_index(op.f('ix_project_memberships_id'), table_name='project_memberships')
    op.drop_table('project_memberships')
    op.drop_index(op.f('ix_parse_errors_project_id'), table_name='parse_errors')
    op.drop_index(op.f('ix_parse_errors_id'), table_name='parse_errors')
    op.drop_table('parse_errors')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notification_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_integration_credentials_user_id'), table_name='integration_credentials')
    op.drop_index(op.f('ix_integration_credentials_project_id'), table_name='integration_credentials')
    op.drop_index(op.f('ix_integration_credentials_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_host_filter_views_user_id'), table_name='host_filter_views')
    op.drop_index(op.f('ix_host_filter_views_project_id'), table_name='host_filter_views')
    op.drop_index(op.f('ix_host_filter_views_id'), table_name='host_filter_views')
    op.drop_table('host_filter_views')
    op.drop_index(op.f('ix_dns_records_project_id'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_id'), table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_domain'), table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_agents_project_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_user_sessions_token_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_security_policies_id'), table_name='security_policies')
    op.drop_table('security_policies')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_llm_providers_user_id'), table_name='llm_providers')
    op.drop_index(op.f('ix_llm_providers_id'), table_name='llm_providers')
    op.drop_table('llm_providers')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vulnerability_database_id'), table_name='vulnerability_database')
    op.drop_index(op.f('ix_vulnerability_database_cve_id'), table_name='vulnerability_database')
    op.drop_table('vulnerability_database')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_identity')
    # ### end Alembic commands ###
