"""ingestion quality columns on ingestion_jobs

Revision ID: c81a9d2e1f47
Revises: ba03c988c559
Create Date: 2026-05-15 07:45:00.000000

Adds two columns to ``ingestion_jobs`` so the UI can surface parser
ingestion quality:

* ``skipped_count`` — how many records the parser dropped (default 0).
* ``parser_warnings`` — short freeform string describing what was
  skipped (e.g. "3 malformed JSON, 2 missing required fields").

Both default to safe values so existing rows back-fill cleanly.

Hand-written (not autogenerated) to keep the migration tightly scoped
to its named subject — autogenerate against the real DB also flags
several unrelated index drift items left from the pre-Alembic
hand-rolled migrations, which belong in their own cleanup pass.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81a9d2e1f47'
down_revision: Union[str, None] = 'ba03c988c559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'ingestion_jobs',
        sa.Column(
            'skipped_count',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )
    op.add_column(
        'ingestion_jobs',
        sa.Column('parser_warnings', sa.Text(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column('ingestion_jobs', 'parser_warnings')
    op.drop_column('ingestion_jobs', 'skipped_count')
