#!/usr/bin/env bash
# Alembic round-trip sanity check (v2.42.0; runs in the backend image since
# v2.390.2).
#
# Boots a throwaway Postgres in Docker, runs ``alembic upgrade head``,
# walks back through every migration via ``alembic downgrade -1`` until
# we hit the baseline, re-runs ``alembic upgrade head``, then runs
# ``alembic check`` (model ↔ migration drift).  Any step that errors out
# fails the script with a clear summary so an operator sees which
# revision's downgrade is broken.
#
# Each migration ships with a ``downgrade()`` body in this repo; this
# script is what ensures those bodies actually work before a release.
# Without it, a broken downgrade silently bitrots until the day someone
# tries to roll back in prod.
#
# Alembic runs INSIDE the backend image with ./backend mounted over /app
# (the host has no alembic; the previous version called the host's and could
# not run here).  The throwaway Postgres and that container share a private
# Docker network — nothing is published and the dev database is never
# touched.  Build the image first if it is missing (docker compose build
# backend).
#
# Run with:  ./scripts/test-alembic-roundtrip.sh
# Or:        make alembic-roundtrip

set -euo pipefail

CONTAINER="${ALEMBIC_TEST_CONTAINER:-nm-alembic-roundtrip-pg}"
NETWORK="${ALEMBIC_TEST_NETWORK:-nm-alembic-roundtrip-net}"
DB_USER="${ALEMBIC_TEST_USER:-nmaptest}"
DB_PASS="${ALEMBIC_TEST_PASS:-nmaptest}"
DB_NAME="${ALEMBIC_TEST_DB:-nmaptest}"
PG_IMAGE="${ALEMBIC_TEST_IMAGE:-postgres:16}"
BACKEND_IMAGE="${ALEMBIC_TEST_BACKEND_IMAGE:-networkmapper-backend:latest}"
# Stop AT the baseline.  The loop used to continue past it to `base`, which
# could never pass: the baseline's downgrade is autogenerated "drop the entire
# schema" and has drifted from the objects that actually exist (it drops
# ix_security_findings_id, whose table a later revision renamed).  Nobody
# rolls back below the baseline — that is an empty database, and the recovery
# path there is the pre-deploy dump.
BASELINE_REVISION="${ALEMBIC_BASELINE_REVISION:-b46cd59c17f5}"

BACKEND_DIR="$(cd "$(dirname "$0")/../backend" && pwd)"

cleanup() {
    docker rm -f "${CONTAINER}" >/dev/null 2>&1 || true
    docker network rm "${NETWORK}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

if ! docker image inspect "${BACKEND_IMAGE}" >/dev/null 2>&1; then
    echo "Backend image ${BACKEND_IMAGE} not found — run 'docker compose build backend' first." >&2
    exit 1
fi

echo "[1/6] Starting throwaway Postgres (${PG_IMAGE}) on a private network…"
docker network create "${NETWORK}" >/dev/null
docker run -d --rm \
    --name "${CONTAINER}" \
    --network "${NETWORK}" \
    -e POSTGRES_USER="${DB_USER}" \
    -e POSTGRES_PASSWORD="${DB_PASS}" \
    -e POSTGRES_DB="${DB_NAME}" \
    "${PG_IMAGE}" >/dev/null

echo "[2/6] Waiting for Postgres to accept connections…"
for i in {1..30}; do
    if docker exec "${CONTAINER}" pg_isready -U "${DB_USER}" -d "${DB_NAME}" >/dev/null 2>&1; then
        break
    fi
    sleep 1
done
# pg_isready answers during the image's init restart; give it a moment.
sleep 2

# Steps 3–6 run in ONE backend container (a container per `alembic` call would
# cost ~2 s × every revision).  set -e inside: the first failure stops it.
docker run --rm \
    --network "${NETWORK}" \
    -v "${BACKEND_DIR}:/app" \
    -e DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${CONTAINER}:5432/${DB_NAME}" \
    -e JWT_SECRET_KEY=alembic-roundtrip-test-only \
    -e CREDENTIAL_ENCRYPTION_KEY=alembic-roundtrip-test-only \
    -e BLUESTICK_SKIP_DB_INIT=1 \
    -e BASELINE_REVISION="${BASELINE_REVISION}" \
    --entrypoint sh \
    "${BACKEND_IMAGE}" -c '
set -e
cd /app
echo "[3/6] alembic upgrade head (forward chain)…"
alembic upgrade head
echo "[4/6] Walking the chain backward via alembic downgrade -1…"
while true; do
    current=$(alembic current 2>/dev/null | awk "/^[a-f0-9]/ {print \$1; exit}")
    if [ -z "$current" ]; then echo "  reached base (no current revision)"; break; fi
    if [ "$current" = "$BASELINE_REVISION" ]; then
        echo "  reached baseline $BASELINE_REVISION — stopping"; break
    fi
    echo "  downgrading from $current…"
    alembic downgrade -1
done
echo "[5/6] alembic upgrade head (forward chain again, to verify idempotency)…"
alembic upgrade head
echo "[6/6] alembic check (models vs migrations)…"
alembic check
'

echo
echo "✓ Alembic round-trip passed.  Every downgrade() inverted cleanly and the models match the migrations."
